<a href="https://colab.research.google.com/github/sskboonmee/data_viz_2022/blob/main/FinalExamGroupCleme.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Final Exam: งานกลุ่ม Final ที่อาจารย์สุ่มให้
ให้นักศึกษาสร้าง Dashboard แสดงรายงานเกี่ยวกับข้อมูลการตรวจโรค(ov) จาก ไฟล์ alldb.csv และ hospital_list.xlsx

#รายชื่อสมาชิกกลุ่ม Cleme
* นางสาวศศิกานต์ บุญมี รหัสนักศึกษา 6232020539-9 
* นายชยากร จันทร์ลุน  รหัสนักศึกษา 623020517-9
* นางสาวชนิกานต์ สุขเสน รหัสนักศึกษา 623020995-3
* นางสาวชลธาดา ดำริวงษ์ไพศาล  รหัสนักศึกษา 623020434-3

#Dashboard

https://datastudio.google.com/s/oZd_rZYawm4

#ImportData

In [1]:
import pandas as pd   #import panda 
import os

In [2]:
from google.colab import drive        #นำเข้าข้อมูลจากไดร์ฟโฟลเดอร์dataviz_2021_data 
drive.mount('/content/drive')  
path = '/content/drive/My Drive/dataviz_2021_data'

Mounted at /content/drive

#Dataalldb

In [3]:
alldb = pd.read_csv(os.path.join(path,'alldb.csv'))   #แสดงข้อมูล alldb
alldb

,Unnamed: 0,user,RowKey,care,date,ov,phone,site,time,urine,pid,PartitionKey,title,age
0,0,test,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,data is not completed,data is not completed
1,1,04857,136FD222-FD9F-4E54-AE1F-7282A276B085,NaN,2022-02-24,NaN,"iPhone10,4",05310,10:50:32,NaN,NaN,NaN,data is not completed,data is not completed
2,2,NaN,1E6D3D62-4C8A-4F8E-90D1-0DC5BC2752DF.png,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,data is not completed,data is not completed
3,3,3450101576642,2D331FB0-CBA2-4586-A5B0-CB3CF44DD9FE,NaN,2022-02-23,0,"iPhone13,4",05087,09:59:47,ปกติ (เหลืองใส),NaN,NaN,data is not completed,data is not completed
4,4,3450101576642,45197AF7-7CB4-470C-9ABB-37C092BD6B21,NaN,2022-02-23,NaN,"iPhone13,4",05087,09:44:06,ปกติ (เหลืองใส),NaN,NaN,data is not completed,data is not completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40030,40030,NaN,6B5FA20F-190E-4021-8547-C12308024C6C,NaN,NaN,NaN,"iPhone13,4",01234,NaN,NaN,5,เกษศิรินทร์ ไชยลาภ,data is not completed,data is not completed
40031,40031,NaN,F48C51C0-A345-40D6-93F4-46213267E1B1,NaN,NaN,2,"iPhone10,5",01234,NaN,ปกติ (เหลืองใส),5,เถลิงเกียรติ เสริฐเลิศ,data is not completed,data is not completed
40032,40032,NaN,A986BDAA-6D7C-4017-8E62-A3C104E946B9,NaN,NaN,1,"iPhone13,4",01234,NaN,ปกติ (เหลืองใส),1,เสรี,data is not completed,data is not completed
40033,40033,NaN,bbuogxulur.png,NaN,NaN,NaN,Samsung SM-A115F,01234,NaN,NaN,1,เสรี,data is not completed,data is not completed
40034,40034,NaN,zttpqogiso.png,NaN,NaN,1,Samsung SM-A115F,01234,NaN,ปกติ (เหลืองใส),1,เสรี,data is not completed,data is not completed

In [4]:
alldb.head()  #แสดงหัวตาราง

,Unnamed: 0,user,RowKey,care,date,ov,phone,site,time,urine,pid,PartitionKey,title,age
0,0,test,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,data is not completed,data is not completed
1,1,04857,136FD222-FD9F-4E54-AE1F-7282A276B085,NaN,2022-02-24,NaN,"iPhone10,4",05310,10:50:32,NaN,NaN,NaN,data is not completed,data is not completed
2,2,NaN,1E6D3D62-4C8A-4F8E-90D1-0DC5BC2752DF.png,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,data is not completed,data is not completed
3,3,3450101576642,2D331FB0-CBA2-4586-A5B0-CB3CF44DD9FE,NaN,2022-02-23,0,"iPhone13,4",05087,09:59:47,ปกติ (เหลืองใส),NaN,NaN,data is not completed,data is not completed
4,4,3450101576642,45197AF7-7CB4-470C-9ABB-37C092BD6B21,NaN,2022-02-23,NaN,"iPhone13,4",05087,09:44:06,ปกติ (เหลืองใส),NaN,NaN,data is not completed,data is not completed

##เลือกเฉพาะคอลัมน์ที่สนใจ

In [5]:
alldb1 = alldb[['user','RowKey','date','ov','phone','site','time','urine','PartitionKey']]  #เลือกคอลัมน์ที่เราสนใจ
alldb1

,user,RowKey,date,ov,phone,site,time,urine,PartitionKey
0,test,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,04857,136FD222-FD9F-4E54-AE1F-7282A276B085,2022-02-24,NaN,"iPhone10,4",05310,10:50:32,NaN,NaN
2,NaN,1E6D3D62-4C8A-4F8E-90D1-0DC5BC2752DF.png,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3450101576642,2D331FB0-CBA2-4586-A5B0-CB3CF44DD9FE,2022-02-23,0,"iPhone13,4",05087,09:59:47,ปกติ (เหลืองใส),NaN
4,3450101576642,45197AF7-7CB4-470C-9ABB-37C092BD6B21,2022-02-23,NaN,"iPhone13,4",05087,09:44:06,ปกติ (เหลืองใส),NaN
...,...,...,...,...,...,...,...,...,...
40030,NaN,6B5FA20F-190E-4021-8547-C12308024C6C,NaN,NaN,"iPhone13,4",01234,NaN,NaN,เกษศิรินทร์ ไชยลาภ
40031,NaN,F48C51C0-A345-40D6-93F4-46213267E1B1,NaN,2,"iPhone10,5",01234,NaN,ปกติ (เหลืองใส),เถลิงเกียรติ เสริฐเลิศ
40032,NaN,A986BDAA-6D7C-4017-8E62-A3C104E946B9,NaN,1,"iPhone13,4",01234,NaN,ปกติ (เหลืองใส),เสรี
40033,NaN,bbuogxulur.png,NaN,NaN,Samsung SM-A115F,01234,NaN,NaN,เสรี
40034,NaN,zttpqogiso.png,NaN,1,Samsung SM-A115F,01234,NaN,ปกติ (เหลืองใส),เสรี

##กำจัดค่า Missing

In [6]:
alldb1.isnull().any()  #ขึ้น True แสดงว่ายังมีค่า Missimg

user            True
RowKey          True
date            True
ov              True
phone           True
site            True
time            True
urine           True
PartitionKey    True
dtype: bool

In [9]:
alldb2 = alldb1.dropna()  #จัดการ Missing ด้วยการ dropna
alldb2

,user,RowKey,date,ov,phone,site,time,urine,PartitionKey
185,85879,shmpdrmtgc.png,2022-03-24,0,OPPO CPH2293,05194,13:08:39,มีตะกอน,0000
186,45-161,D2CABB8C-533B-450A-AFA6-B693749CC1C6,2022-02-23,0,"iPhone11,8",04312,09:45:28,ปกติ (เหลืองใส),0-1528
187,45-161,57A5F06C-C840-49EA-9514-A30D3C897CC8,2022-02-23,0,"iPhone11,8",04312,10:06:45,ปกติ (เหลืองใส),0-1544
188,27529,ADC54E82-4225-4DE6-89A6-A7E556C15FB1,2022-02-25,0,"iPhone13,1",04999,14:22:22,ปกติ (เหลืองใส),0000
190,06223,kfpwuaqldj.png,2022-03-23,0,Xiaomi 21081111RG,13777,16:31:45,ปกติ (เหลืองใส),00000
...,...,...,...,...,...,...,...,...,...
40013,ttest,crqcufokmn.png,2022-02-21,2,Samsung SM-G998B,test,14:23:45,ขุ่น,x001
40014,ttest,gzxgflnowr.png,2022-02-21,2,Samsung SM-G998B,test,14:23:43,ขุ่น,x001
40016,xxx,jytlopevha.png,2022-02-17,3,Samsung SM-N950F,xxx,00:01:06,ปกติ (เหลืองใส),xxx
40022,yyy,ivccsksowb.png,2022-02-17,2,Samsung SM-N950F,yyy,08:41:05,มีเม็ดเลือดแดง,yyy
40023,zzz,psudrnccsh.png,2022-02-17,2,Samsung SM-N950F,zzz,08:41:04,มีตะกอน,zzz

In [8]:
removes = alldb1.shape[0] - alldb2.shape[0]   #เชคว่าจากการดรอปข้อมูลหายกี่เปอร์เซนต์ ซึ่งพบว่าหาย 3.427001373797927% ของข้อมูลทั้งหมด ยอมรับได้
print(f'size before drop = {alldb1.shape[0]}')
print(f'size aftre drop = {alldb2.shape[0]}')
print(f'we loss {100*(removes/alldb1.shape[0])}% of data')

size before drop = 40035
size aftre drop = 38663
we loss 3.427001373797927% of data

In [10]:
print(alldb1.shape)   #จำนวนแถวก่อนDropna
print(alldb2.shape)   #จำนวนแถวหลังDropna

(40035, 9)
(38663, 9)

In [11]:
alldb2.isnull().any()   #เชค Missing พบว่าขึ้น False แสดงว่าไม่มี Missing แล้ว

user            False
RowKey          False
date            False
ov              False
phone           False
site            False
time            False
urine           False
PartitionKey    False
dtype: bool

##จัดการข้อมูลให้เป็นไปตามข้อกำหนดของอาจารย์

###User เป็นตัวเลข 5 หลัก (ตัวเลขเท่านั้น)

In [13]:
alldb3 = alldb2[(alldb2['user'].astype(str).str.isdigit()) & (alldb2['user'].str.len() == 5)]  #เลือกข้อมูลที่เป็นตัวเลข 5 หลักเท่านั้น
alldb3

,user,RowKey,date,ov,phone,site,time,urine,PartitionKey
185,85879,shmpdrmtgc.png,2022-03-24,0,OPPO CPH2293,05194,13:08:39,มีตะกอน,0000
188,27529,ADC54E82-4225-4DE6-89A6-A7E556C15FB1,2022-02-25,0,"iPhone13,1",04999,14:22:22,ปกติ (เหลืองใส),0000
190,06223,kfpwuaqldj.png,2022-03-23,0,Xiaomi 21081111RG,13777,16:31:45,ปกติ (เหลืองใส),00000
191,12015,00859DB9-1BD9-4825-B246-3DC25EFD1924,2022-03-30,4,"iPhone12,3",06307,14:46:08,ปกติ (เหลืองใส),00001
192,91811,1376ACA2-AFA5-4457-967A-D2FCF908E6A5,2022-03-30,4,"iPhone14,3",05328,15:27:45,ปกติ (เหลืองใส),00001
...,...,...,...,...,...,...,...,...,...
39812,99999,F45E78D3-7D89-47A3-8207-C705377E0E0A,2022-03-11,1,"iPhone14,2",99999,11:36:34,ขุ่น,99999
39813,99999,lnlohgqckf.png,2022-03-10,0,Samsung SM-G998B,99999,18:10:29,มีตะกอน,99999
39814,99999,vkdocpmjiv.png,2022-03-10,1,Samsung SM-G998B,99999,12:14:41,"ขุ่น, มีเม็ดเลือดแดง",99999
39815,99999,vrvyfnvayq.png,2022-03-10,1,Samsung SM-G998B,99999,13:58:01,ปกติ (เหลืองใส),99999
39816,99999,zuhbtvyrce.png,2022-03-10,1,Samsung SM-G998B,99999,13:57:58,ปกติ (เหลืองใส),99999

###RowKey เป็น String

In [14]:
set(alldb3['RowKey']) #ดูค่าในคอลัมน์ RowKey

{'4346F0E7-DECE-403B-BC50-1F1EBEE3D24B',
 'kinfvzkdpx.png',
 'DA3A9FBD-63C1-424E-ADBF-C42AE2F3AD76',
 'tymwelyyzw.png',
 '1A0793C5-026C-4E13-9FA3-9B31EDDD4089',
 'ipvgkzbqjj.png',
 '9DF98818-64F4-4125-AB34-66F399D55C9C',
 'orebkqzpaa.png',
 'E91B569D-C9B2-4880-8320-BF6BAA3D1E8D',
 'dgcofpbcwg.png',
 'C40A3F6A-A74E-4342-B4EF-C253793E63B0',
 '2B683123-46A5-4503-9A84-E008EF6E7113',
 'xhbtpsyzum.png',
 'qfrlvbtylt.png',
 'focslnetqc.png',
 'DBDB7A4A-6077-4946-AAEC-CA19509747E3',
 'BBF3A23D-8E9F-46FC-A257-0BFBF5097FD1',
 '34020511-560F-4144-8533-03B21FE90F28',
 'rrdlbppodz.png',
 'jcpqlcbjpj.png',
 '2DAB51C9-62F4-450E-8FA7-52A9EEDA9DF9',
 'einhtvwjdv.png',
 '6F3A6894-C850-4640-B196-7968C3E6737B',
 'D63651F6-5079-4DD4-8529-83231DAB99A0',
 '3DF6641C-6E88-4C6F-84B1-D1E88C8A4AC2',
 'srywrbpfbe.png',
 '03E2D7DC-FBA4-44AC-9889-4D343A81E8FB',
 'cplbnzkjoy.png',
 'chhoocypip.png',
 'qplhjqchac.png',
 'mwfxrvvtyo.png',
 'mhgvvehfxb.png',
 '811DD604-3407-40CF-9F81-DAAE11DDD5BC',
 '56BCF415-53EF-4EAB-83D2-DFB5F9B8E11F',
 'dbdpvkdfej.png',
 'krtqlkgcyc.png',
 '031879EB-2469-4F10-91F8-16E705AC2821',
 '6FFDCC1E-AE98-407A-A202-E2499BD79ADE',
 'wbexoavjto.png',
 '1A2032E6-3B13-47E2-9F62-A1DADE2103A0',
 'vqaljcjrgx.png',
 '79B84331-4DB2-4A2D-BC36-550F9939191B',
 'vhbndkzbdx.png',
 '5A74102E-9CDC-4E95-92DC-12419B3A2630',
 '32E6F89A-C7C2-49AD-B3FC-970FF7D34787',
 'jxzoraaetb.png',
 '63FA4E67-8199-456E-9626-0F198598642E',
 'zwwrdbejlc.png',
 'gwfytjsmfy.png',
 'pwdcrkhueu.png',
 'alemgtujmp.png',
 'tyfehogsig.png',
 '2AA4361B-21F9-4608-BD89-9BB770F588D0',
 'vdqmmoihyv.png',
 '5D996526-54C8-4570-8329-C24229C6B648',
 'B48DB3C0-4675-4DDC-A5AF-04E0F42B5578',
 'knootkuvxc.png',
 'syfsthjbrl.png',
 '33261578-A70E-418F-802D-049E84D1508E',
 'BD0FA443-BDCF-4D27-B0F1-3F32FE6E0179',
 'lccypseepx.png',
 'FA93936F-CFD4-4C18-A97E-244348D14783',
 '6696B48F-F047-4C25-9514-6ECAA58ED68C',
 'oltukxrtlo.png',
 '0484D17F-1A9E-4227-8A0E-0E06F50BA31D',
 'glqhvwfkrb.png',
 'DB5F0C42-9C57-473A-AA9B-C8E3D0FA51A8',
 'aklvjqclgq.png',
 'FD38BD09-0345-4BC8-9B63-646710AF884F',
 '29BDA0E8-2BBA-4C83-87C8-8C211777D283',
 'F18B1032-C593-4652-83E0-82D93F97A5D6',
 '2F40697E-2253-42AE-B170-BFBDCBF5D283',
 'qiokernans.png',
 'E6BA9CD6-1A5D-440A-9C47-3E9FD4185746',
 'qpplaovhjw.png',
 '85971D04-D1D9-43DD-9887-6B79A659B62F',
 'ypfjucrvkb.png',
 'eogxshdgmu.png',
 '656FD55D-4AC4-4DE4-BD38-788639C992A8',
 'mscxfkebkg.png',
 'FBD9F3C2-3679-423B-807B-584E398F54BF',
 'C8BFABCF-E200-4DB8-A8CD-B511F0E8D3B6',
 '5ED66ED5-FABF-4D3F-A9B2-9059B2745D54',
 '35192907-AA8A-42FE-AB3C-BEFBD7E71B5E',
 'F2AED478-FDA4-40BD-8A3D-459A4513F536',
 '36E8B916-4112-413F-BC1F-688086202671',
 '51DC3427-F16C-466E-991D-5ED28D3404C0',
 'offpenjnvm.png',
 'qdkxxkwnwm.png',
 'rgomontdxw.png',
 'ECFF49D2-9DB2-4F39-8536-E757B0637323',
 'zoydxyxhth.png',
 'daurnkanae.png',
 '5563C9F7-DE2D-49A4-A247-4023ACC6897E',
 '78743F97-084E-4F21-A10E-0D8329088C37',
 'D35427E8-8B0F-4C74-902B-385258B331FF',
 'uhtafjsgml.png',
 'AE700756-CAA5-4995-A5DE-A603D9BA4C3F',
 'uzhzkkcitu.png',
 '17A77E98-ED1F-4F05-B063-DFFCDFC74B12',
 'kqlnkaevuc.png',
 'sfykhpocmp.png',
 'D78728C3-2F8A-49AF-9E4B-F013FE6A9BF6',
 '80474A60-6C30-4215-B154-63872C8AB75F',
 'FFFEEC8F-1E45-47EE-9E9C-7F66E9A915B1',
 'xfnfdkhtdq.png',
 'fdbmqxqboo.png',
 'FC5664B4-89F6-4DEF-8872-27E67F9DAEDD',
 'cfywiyrixi.png',
 'qzkqlabwcy.png',
 '7C041F5E-6F11-401A-AC3A-3A58473689C1',
 '89613DD2-B9C8-41E5-B508-5AD38DB0C8C2',
 'B91A8DA3-2C2E-48A4-9DB3-21CF41176869',
 '681D219C-F267-491C-A114-53D4F3471832',
 'wmmcmrkmdh.png',
 'whugbdwdnp.png',
 'A2D5DE4C-8E60-41E6-97C2-4F3AE0557CF5',
 '68D78DD3-F8C5-4685-8C94-58EACA0BEA76',
 'A2FFE170-52FF-4625-B8D2-A829B284366D',
 '14CF8826-0CB8-4101-98F9-66BDFED111D1',
 'tehmuuqkuy.png',
 'xpzqmekhvi.png',
 'fmvujhadlp.png',
 '9E4F35A8-AE03-464B-B31A-1D5F39589922',
 '9D48F19E-C353-4147-BCC2-0E64C633D1EA',
 '7FBC8C5F-26C4-44AD-9F6E-5CECE3E0724C',
 'nxnjzpqyip.png',
 'greusssozq.png',
 'nblndvxnnd.png',
 'llyzjurdcu.png',
 'B0C69AC8-97E9-4802-8F88-8CE037979AF6',
 'D8E5A043-EA25-4523-AC89-CC53A4C99A31',
 'huknxkkciz.png',
 '1C43A4F7-374A-417D-91AE-D4E62F91F3BA',
 'AA28B5FE-BB49-4305-A295-DEB7B1D55C21',
 '2551B71A-1471-4A5B-8ACB-C4050F746558',
 'aehqviikwk.png',
 'tyvkmwdpvd.png',
 '820F640B-8AD3-4D3F-9CC5-8884F324AB3F',
 'arzkzrhgep.png',
 'qipqmkjydy.png',
 'gmbkgifoij.png',
 'jgbgsfvldx.png',
 'jklzvvrmmc.png',
 '1E8C46CD-A800-4FB3-A619-861F1F8D3E4E',
 '80F539C3-BDA2-4977-A7F4-144E858F1C53',
 '71F9AB12-759C-4C6F-9D6A-FCD01E0B59CA',
 '2D2A421D-38B0-464B-9320-4F305FD0A505',
 'E981E57A-61A0-48AA-805B-044D6681696D',
 '8943665B-259A-49F2-B8F6-DC031F0C4345',
 '6A5CFD9E-1320-49DA-912F-C266166FCCB2',
 'nvkxadvcxi.png',
 'nqyjhmiwra.png',
 '02CB346A-94A5-4CA2-82FD-ADD68F6BCE18',
 'otrbqlkgdo.png',
 'dmigtlyarz.png',
 'nhxgsrfawk.png',
 'bqiwliqzel.png',
 'pwhkgoonjp.png',
 '637CE352-22D1-40C9-A1F2-BEAF364A4633',
 'F237AAFF-F5F0-4FB8-A825-E0958D2B081C',
 'bjjooxqcwu.png',
 '6DA703C3-6C9D-49F8-BFC7-86B67C3EC56F',
 'tqpdxawcxu.png',
 '6CCE8E24-4B22-4CDA-A52E-B3EA8B95D5C1',
 '97DE2651-8E62-4F00-BF48-96345768E03F',
 'gknpywnzob.png',
 'D5C99A09-C8E4-4B44-87EC-A147C78E7BF5',
 'EE15DE8A-3F14-4DA6-B1D8-4826B81A7745',
 '3C32F030-DD62-4ECA-853D-647BF3D29EA7',
 '4AB1DEE3-FDA4-4274-9D32-F2AEE77C0B19',
 'dmfowmsisc.png',
 '6CAC4856-1546-44FC-A9AD-6E79881D8E22',
 'qtwafmirsd.png',
 'ahsgxyokpc.png',
 'hkhwiuasil.png',
 'ACECFB87-659E-4623-91E9-CC0C1FF8F02B',
 'kcpgnenswk.png',
 '7B03B1A9-AB04-453A-BABD-EF814AE09D13',
 'avhowjbtag.png',
 'qvnendtnyb.png',
 'oekodkmqbd.png',
 '803E72EF-1398-453E-A8F1-571BC3F8A893',
 '33255113-A15E-4495-B1E7-1469E772B535',
 'D4B88257-DCAD-42B8-B306-729D73D2B9FF',
 'pivuxbuqsx.png',
 'C13E1291-2DA4-4C0E-8730-983BF22A36A4',
 '8FC18CA6-4ADB-436D-9861-0148C3068758',
 '153532DF-F5C0-412C-BBA3-B712E82746C8',
 'clnnngdcwq.png',
 'yregvexzwb.png',
 'yegkgnkaiq.png',
 '941EC8FA-249B-4541-A592-5C198388D2F6',
 '9FA0B155-D5FF-425F-BDE5-80D3B9C5CF36',
 'twmwidhmfx.png',
 '3AB6BDBD-1A84-45D6-B2CE-99D2CDBE02D7',
 '60CEA451-92EF-4ECC-A4CA-54CA30ECDF22',
 '1746F30C-F49A-4671-9BA8-897CAC880D3E',
 'kfqjbpvggr.png',
 'hemsdyazlj.png',
 'wgtabjrnsc.png',
 'B4A439C3-E24B-4446-BE89-773981B74E8E',
 'A0BD29D9-5500-451E-9AD3-CA07FB4730B4',
 '4389C954-E1FB-4E90-BCD6-F04724D8D317',
 '6A88076C-05B2-42D1-A131-065960B20837',
 'A70D7E08-C837-48EE-A3B2-6B4E1F1B79A5',
 '39DF950A-84D8-4EF2-9E70-5FEADCA18EF7',
 'lxjsnckekt.png',
 'qarqisbvkq.png',
 '6694E32F-E00F-42B6-BDB1-01C50E3E6E78',
 'FC55095E-688C-4537-90D0-88A84F354666',
 'ijgoufdxui.png',
 '58385A0E-53F1-4940-AE54-3DFAEB8D326C',
 'tktvgmtusp.png',
 '5ED5BF37-39BC-44A1-8300-93ABDB10F194',
 'CFFDC2BC-133A-4AA0-A218-A57432B53A8C',
 'vcpnpemydm.png',
 '71E73468-2764-4D71-BBFF-C65C29CD06F9',
 'vndhyquimt.png',
 '4A242689-1692-47CD-A177-6E248B355209',
 'xhpqgjbfym.png',
 'pqlssxkmfx.png',
 '720C71C6-0A07-4F39-8FB7-257DC1165A42',
 '7929A286-5363-4E20-8BF5-C61ADD6D98E0',
 'rjbiofethd.png',
 'E6909E33-EDF9-4E8C-A3A1-1C828F697AC1',
 '16D37A19-7E36-4049-8334-B3BF0AA9BE81',
 'mrnkwsczwa.png',
 'A5C712C3-B5F1-4FB5-940B-E56E91DFEFCB',
 'klycecpnli.png',
 '366F4E53-99A4-4237-ACC2-9EFFDBDD0654',
 'zpriswjpyo.png',
 'F11416EF-24D0-46BE-AD59-2E352DAB60E6',
 'EA0FE848-56A8-4D4C-BE75-DAC61B9FE1D9',
 '45C6AFE3-B1E1-4498-A863-E61C4C207DEA',
 '23BFD6E6-6DF0-4E30-BC80-B99DCE9C1D18',
 'sdjjimgwwg.png',
 'sqvvhuoftb.png',
 '4B24E4E5-1C22-4899-9691-52006811F94D',
 'ztikjgrmdh.png',
 'vpqiacymsl.png',
 '1AAAB26F-8F4C-448F-82DA-EF297FB303E6',
 'qkviqbwmuo.png',
 'jpirroawwq.png',
 'tlbjvdivum.png',
 'ekyxhcouws.png',
 'mggevovjtd.png',
 '5F088C00-8082-48A7-B7BB-99F7BB6384AE',
 'foumwjoybu.png',
 'AB6EEEA3-F631-48CF-8368-9E4C5F7B2928',
 'E3DE5552-00E3-47C4-A740-F2B1E016D83E',
 'mtrdybgrye.png',
 'F52B4CE4-3B48-4F1F-88C0-1EE7FCF48BED',
 'tnsbtmlmar.png',
 'muzqzluddq.png',
 'djjpyfxoxo.png',
 'gxllnoxkib.png',
 '39AA28DE-C755-4FF5-9CC8-4A3240148F17',
 '82304D36-FB31-4CAA-BDF9-3BD6667A1C3C',
 '15EF6FD4-23FC-462B-B9E9-2B323E6602DB',
 'hnkbotcmbo.png',
 'DA479593-4C82-4BB2-94B1-DB06899EB590',
 'AE878BFF-127B-4D77-8FFE-43370E666B3B',
 'E5A004FB-BDEC-491C-8927-EEFC9CF5F065',
 '10A986CE-A22E-4332-A93E-C4D3DA59AB38',
 '0D95B25B-1513-40CF-9EC6-14D523B68866',
 'A7CA7E34-4FBB-4636-A76D-E06B8134A942',
 'DDFDD88D-AE45-4CB3-B367-982CCF13E6AF',
 '3C417096-2A59-498D-869D-5183CCEC591E',
 'rvuphjsezg.png',
 '55CE9A40-21E2-4014-9C1A-462E8A7BD853',
 'F004B30C-1B95-4549-B043-7D7AE1F2882A',
 'renouonlag.png',
 'DE1AB80C-6F06-4820-9CBC-A436362917A5',
 '54EB3ECD-8604-484E-A808-644CD6D85663',
 'itkjcjrdhi.png',
 'inoytmfwzs.png',
 'A75BA2C5-0AB1-4C06-9D98-781DCC6945F5',
 'fzovrhpqwh.png',
 'gqehmhiakh.png',
 'ybnermtcwr.png',
 'ctkgmtxykh.png',
 'fnayrvsfkc.png',
 'wqszxsnlrt.png',
 'C8D88D88-7A99-49A8-915A-AB77DB8EB452',
 'odsrpzjdmi.png',
 'rprsaajyqj.png',
 'hdfokkshli.png',
 'ztijmyrrmh.png',
 '1A64F2E8-9535-4962-A41B-2259F8FBFA0B',
 'F5E79C9C-A473-472A-A5AF-524A5A807962',
 'nqrjtgndst.png',
 '6F58EEF5-1397-41D9-981D-63FB7BCEECC1',
 'fggkduoppx.png',
 '99C19FF6-7853-4FF6-9E63-08431207455C',
 'axjgajefgh.png',
 '60879F9D-A146-4FE5-B563-D7A67B98C56E',
 'A39F8EB2-9AF7-4546-A7C9-A5E6F395D5BE',
 'wqnpjcyjed.png',
 'oyslegbsud.png',
 '5FFA6B57-15E8-45D7-A15D-F8BEE9D8EED2',
 'dnxxadidxx.png',
 'C7E556E1-1E06-446E-AB74-CF76C1F0C4C8',
 'vpxrlwdlvh.png',
 '436EA22C-A1B8-4758-A0BE-692BBE9C8BDD',
 'rkaghcpifw.png',
 'A60CB9B2-9FB7-4844-B708-722AC90A9F18',
 'AFE075F6-C7BF-4F84-8EFD-F57B9057A0B2',
 'A147895C-C1CA-405F-BC3D-3F85C2657C3E',
 'umenavzuws.png',
 '6F7A2769-0A76-4372-97DB-C88CD24EF8E6',
 'FBC1C903-9271-482B-8434-732E6517B64A',
 '069FF814-F02B-4C8F-A163-D4B280075DE1',
 '0A2E3A64-FDBF-4CBF-963C-B067CA948346',
 '8BA247E2-EE55-4184-A804-5B69F2636DD1',
 'CC5CDAC6-60D7-45E1-BFF5-000425C967DC',
 '697D5E37-DBF7-4D93-A63C-577EA9F0E7E3',
 'jrplwvumuf.png',
 '07268140-6101-4472-BBDA-32ECB33FB1CF',
 'oqjxmjstgr.png',
 'rfuonygusu.png',
 '5B9A7994-FD62-437E-A2CC-DE2E43EF13D4',
 'qcgckzocrz.png',
 'feoxmcwhah.png',
 'fnnxojhhzg.png',
 'omozagdssy.png',
 'mqcstiwijh.png',
 'zceoysfbqo.png',
 'B7200896-F771-4816-B7B1-34920CAD4946',
 'dxsdzqsges.png',
 '747AA928-E4C9-4C97-8A3D-D1F7D613B79D',
 '3CC3BC74-1906-4FF0-95F9-A0675CC86992',
 'apxqqnnfyy.png',
 'csxvpxbtdz.png',
 'ostqdplezb.png',
 'vkcxosjjlk.png',
 'qpynzvfnim.png',
 'ddddsoelqj.png',
 'lxayenqfju.png',
 'eibzpetqfu.png',
 'C823CD5F-937D-42F2-BF88-234BFE9B252B',
 'D485EFDF-8965-43E1-A745-C14E1608E08E',
 'aiveigygxv.png',
 'jdbhuurrwk.png',
 'chxbmvwoun.png',
 '0CADCB0F-9FA9-428C-9182-FC9D3A5C7CC2',
 'mqababzsvr.png',
 '836B14A7-19C7-4882-A165-E59AB1D1A71E',
 'E8AB6979-1C4E-4533-BED3-38295201F6B1',
 '0F054F33-36CE-48AC-BD15-9B3B59DB0BFC',
 'gygptmfmit.png',
 '2228BFCB-E831-426D-A5E8-F014709B9676',
 '7A212B43-1BF2-4A8B-B489-302E79CE6FEC',
 '4159028F-F862-43AB-83FF-4156D28C1E9A',
 '2FE8BC3E-ACC5-45AA-ABED-EE9ABDDA0CF0',
 'CAF799C5-AB77-4C2E-A1EC-A995945F4BBC',
 'eqmorphgst.png',
 'naslzbfxih.png',
 'gxbosbfnwn.png',
 'B9A73499-54FD-436A-A1A8-21CBC4C003B5',
 'cmavvpdmhd.png',
 '40FE596B-2EB1-46C0-B4C3-298E9B72DF29',
 'FAA1D5A1-76A7-4585-9989-6BC96156C7B1',
 '97B2C4CE-F2B5-40BF-A885-FF282BDA147B',
 'A8B84D66-7464-4F34-8734-0832EFB2F70C',
 'nfzxiasuvj.png',
 'tcscbzvwim.png',
 '9B605DE2-3BF5-4E95-B038-236FF2989CA8',
 'C67D7921-BF31-4DEF-8F40-A2B1F0D0183D',
 'yhflreqdrn.png',
 '7D901B15-C7E1-4E9F-AA00-2B94D2130F0D',
 'qcuubfucqm.png',
 '748B9F3A-9C0E-497F-8DFD-7386A86B54C7',
 '513967C4-3646-459B-B919-9E2C8C5AEBD4',
 '5A605AAA-F73E-449D-ADBE-1E455FF6397F',
 'fzgijrryvb.png',
 'DDB322E0-16C1-402C-859D-17E42D753F8F',
 'wfgdiqvvvo.png',
 'B9585B4F-08A0-41AC-B098-18C9653A6772',
 'A093FDAC-3848-4BA5-A153-F6D45F28643C',
 'zoffdswmie.png',
 '0F203907-49ED-4AEA-B86E-8CA0A71FAD65',
 'ykbiuqmiic.png',
 'EFAD5D7F-7A57-4051-9E10-7B78EAFF9C48',
 'zqtrxpzmkv.png',
 '7874A699-3500-4CCB-A958-E1E54E4323A6',
 'C6BD439A-DB8F-4784-A748-1A62B099C351',
 '77CC8415-21BE-4EA0-845C-0294356DC03A',
 'qghrvedtgd.png',
 '5E56E027-8A45-492F-BE46-91BCDF1DE1F8',
 'phaptljevv.png',
 '390DA367-4C01-4E64-BFF4-D09028A275AE',
 'E24B84B9-D542-4031-93D9-3D0E65257133',
 'EC48D1B2-D0D7-421B-9AF1-22FFA31D8B23',
 'kkhpplcixn.png',
 '1B5F0A66-04BE-40FF-AFB7-41BB0BD875DC',
 'pzwylpnwdz.png',
 'F6EBC894-0882-4044-B9C5-2ECC4BDA9ED4',
 'rcshxysjvc.png',
 '740A205E-B7F8-4888-BA8B-0A7413451BFD',
 '821551E2-D234-457D-BFE9-BA09222033BD',
 '72BA70F8-C22C-4EFF-BDAC-AAFED6E3980F',
 '9DB25EE2-D3E2-410D-97DD-6894B27E6DF0',
 'jdjlxdnjiz.png',
 '1761F6D6-3423-4D79-BD46-473B75051018',
 '6E1EBA78-FE3A-46DF-8C39-249A169BE5C8',
 'afsannlpih.png',
 'ED007687-B4C5-4A6D-849C-179430EF5DA5',
 'ujzpxvpobt.png',
 'ofrvvuoypx.png',
 '14C9B710-8740-477B-8CFC-45838B8FB400',
 'hyrvyqjdvg.png',
 '7AC88EB2-DDD5-4C58-814C-DAC7099A5CCA',
 'F30BFFEF-A203-42F1-B9D4-B4FFFBBAA75A',
 'vxvqlwbdbv.png',
 'rfwerfdveq.png',
 'B2E7B9D7-B623-4158-B541-D16388CF10BC',
 'jangajcdqj.png',
 '232CB854-D1D0-421C-A86D-D34AB1395756',
 'vgsemylkry.png',
 'D7BA0479-8AD3-48CA-89DA-35D74BA4F387',
 '018BA2F7-DD99-4287-BE63-47029CBCB407',
 'kdzhcqsuan.png',
 'osmuxxpsvr.png',
 'cmssujjxvm.png',
 '44769694-B544-49F6-8321-141725297C5C',
 '93BB976F-391B-45B9-8BDA-7929B6B4CD0D',
 'gkhtsflzqd.png',
 '71FD74A2-D907-4DC5-9AA6-79BDC9347EC4',
 '5E016C3C-C7DE-4501-9EFC-757FFF6B94AA',
 'trlqisowje.png',
 'qwoaympmgq.png',
 'bjqtutgety.png',
 'rrabfmrulo.png',
 '2F8E7D75-4103-4CE2-AAAC-8C212E54B597',
 '6A56C9B6-5CA5-4D18-9B57-ABC8CA1019D1',
 'cmopsxtnvk.png',
 'csafgpkoty.png',
 'DFC02C1A-9A3C-48C9-86A7-AA6A156E7758',
 '8DED4A55-99C9-4290-8F15-EB095555BFE7',
 'DEDE5792-0D77-41A8-8F2C-7FD8B067F90F',
 'ptjahlwuuk.png',
 'iiudbqcwvt.png',
 'ariyawhjmf.png',
 '1F104199-AECE-4289-B8F5-9AE4CA7DC272',
 'C9D92C77-E8FA-4D75-AA65-D6124410D3AE',
 '0736A0F9-4A57-42B8-A497-33EE5D214948',
 '74F6FAF4-A79A-4FA9-BB2E-04F1D6A4E7F7',
 'bftbawmvxu.png',
 'mzhsuxqksv.png',
 '75ABF30B-411E-4CCC-B8AE-3027FA3028DF',
 'gwkkgcuxas.png',
 'ppnctwteld.png',
 '11B9DF46-DA19-40C0-9717-34ED6DA65617',
 '57111134-BA50-4A9F-A661-AF9DA8917268',
 '30715C48-0EDA-41C8-868F-97C697F11978',
 'ltasewruus.png',
 'gzlkgnqzbu.png',
 'DC9590AA-FC4D-477B-850F-166CB95BC4EB',
 '1F9B04CF-601F-4F83-BA77-ED447F58DE6B',
 'A9EC18DE-6C60-40B9-A4CF-B5999CCD593F',
 'C2D71026-BF47-48C5-A41D-0C3BB433EFAC',
 '45DAC2A7-8A25-4CEC-8C32-3F1361DF5D51',
 'niixmnezod.png',
 'dzqedeoext.png',
 'ssmptkyful.png',
 'vzgpdskskt.png',
 'BE3A4F7F-F4B9-4A7E-AA7D-7A9697F79B40',
 '74F849AF-3DEA-443A-B1B4-2585163E2F25',
 'CD36D25C-C504-4039-8572-6604E4ADC6CF',
 '42C195DA-5E69-4D77-BC2D-D4D7ADD88C50',
 'fhilcinrnf.png',
 'FB21B485-40BD-44C1-981E-EBACEC6722A9',
 'BA06EFA7-7B52-408E-BE53-0EFCA0A5B4F2',
 'frvgwohzcx.png',
 'rvzcpxblsg.png',
 'tcndjmysuy.png',
 'B0699C34-A2AF-4AF3-8357-DA7F2F9AE8FE',
 'AAC8E532-486B-41B1-AC6E-83AF7E6CA236',
 'yiqvgpxmer.png',
 '11BC5B80-E343-482D-BC01-7796559B8E35',
 'agautavorx.png',
 '87F469AB-7135-4487-8B39-9111524A6027',
 'D3FB8DCB-CA61-4977-9D2B-81C2672FBEF7',
 'smyoigwuwj.png',
 'F2E3A478-BFB2-48EF-92EB-3843A792711A',
 'mtaipzuhsw.png',
 '5FA55323-D0C5-48C9-B905-91A843C7BDF7',
 '45264CBF-E5E8-4ACA-A4F6-0DC3AC895B4B',
 'hrhumflocd.png',
 'F3C587D3-9AC7-463C-8D23-D4A0EBA6D7AD',
 'tzefukrrid.png',
 'yaqpwljrpd.png',
 'A38E6FEA-C42C-4910-A755-1810C0BFBCC9',
 '847849DB-316E-4041-B9AF-67EC2CCDB9CB',
 '8CA640EA-28DA-4C53-8571-7BE5E26F9F2F',
 'zjdyrcaarc.png',
 'spjoihkkcz.png',
 'cjsmbyukwz.png',
 'C3AC41F6-D9E2-456F-AF32-F4EAA3586D32',
 'imbpmyrpyo.png',
 'rdsqayzjlc.png',
 'vtdvrzlrye.png',
 'B90E7A0D-B435-4BCF-9ACB-E63BB6A9B10E',
 'E9925C29-65B3-42B5-A8D5-B1C17747400F',
 'FE3A152E-70A7-44DB-9222-6DBF3B331860',
 'rbtrpxvtkn.png',
 '180C87E6-4E9A-4F87-91B7-77904F88A8C6',
 '2358B281-3F1E-4FA1-975F-46A8FA20CB42',
 'cggjykmkua.png',
 'zbowktlwfs.png',
 '5D3B60EC-1326-4FFE-B07C-031A37836558',
 '7E4FCBB9-BA93-4054-A365-891A46BA9243',
 '1F0165E2-CCBB-49DA-BEFB-26D66467AE5D',
 'B42A4EB3-CCB5-4463-B0BD-E0B302CA5C35',
 'gydrvtmxbd.png',
 '32208E56-CB85-48AE-8CD8-5262977CB551',
 '01761D66-F114-4AA4-8ACA-34F424330E67',
 'xmtdwmczss.png',
 'B753D89D-1225-4099-8890-4C51950AC734',
 'jnrwnsdziu.png',
 'DF4D27C5-DB6C-46B2-B608-5EFD0778B6C2',
 'D6B7E314-97AC-4BD1-885E-5C31D7EA28CF',
 'auztatiiec.png',
 '28B3F9AC-6BCF-427A-AF95-6AD8E0FA6C86',
 'gdutfdlbxn.png',
 'BF6EBE8C-8D1D-4FB3-BEFF-1D0A7161235B',
 '10E12052-3886-45C2-9693-15B395E965D6',
 'lyjoxgubcd.png',
 'gqnvpnmnof.png',
 'iqbemfgcbz.png',
 'riuyxvtccv.png',
 'kleiidrcnb.png',
 '127A3979-ED63-481B-B873-61EED06CC36D',
 'pvikatauug.png',
 'nzlqckdtri.png',
 'wqfyhcwkff.png',
 'F345FFAC-2EF7-4FC9-8ED9-74F1559C4C4C',
 '4A64B360-0A93-4EBA-9F2A-D0D05EE2DB1F',
 'vghhzvcmte.png',
 '28AF03D0-177F-4971-AEDA-8C01B8A7BB3A',
 '3DA55B73-75E2-4E08-BD2B-EF0AA78E5141',
 'wfxscvzami.png',
 'urhdcmgbyg.png',
 '0661CFA5-9F57-41D5-A6E0-50D27C8310A6',
 '121C56A6-55D7-4883-A87E-645A45BB10C3',
 'vecqbgclky.png',
 'oytdbesfiw.png',
 'CE26E44E-A280-49F7-98CF-A60EAAF35CBA',
 '53E066AA-EA28-4AF1-8E6A-B8462B5B8D23',
 'bzelrkvjvq.png',
 '02321D21-9873-41EC-B4EB-81FA839F32BD',
 'lbhfltfuso.png',
 'okutpozvii.png',
 'czajfhcomd.png',
 'D4CEBB8A-64AE-45DB-85A5-528599456E59',
 'qcyxngvihf.png',
 'fknorriyzy.png',
 'A589E1E8-110B-480D-901A-69C176266179',
 '12F1FEEA-F686-44AF-A97A-3127AA591774',
 'tuvmsxnrai.png',
 'A9C55229-6838-43B1-8705-9E14613C2498',
 'herwktbhba.png',
 'webehvefzd.png',
 '320F9EF1-3305-4C15-938C-B12E3A4D1451',
 'A037577E-3CA6-4617-BECB-F5D04C4BAF60',
 'icjihmwyoq.png',
 'shwztfectn.png',
 '678C5E99-FEFB-446E-BCBB-5130178FDC26',
 '8170F319-9E61-4F11-B412-12DBBD7ECB95',
 'yjjtuszbnw.png',
 'flaqbemjpg.png',
 '4B0A9C79-DAA2-4F72-8DDD-280288E6145D',
 '8785341F-5AF9-4938-A62D-F7F6C1B942D0',
 'E0254612-4D90-43ED-8100-3B52A507F507',
 'lugdxtygvu.png',
 '5420F83C-A54F-4E16-8AE0-7011DAFF30BE',
 'agjnmmsjtt.png',
 'zapaljiujz.png',
 'uqhyfrhphv.png',
 'ezvaawqepv.png',
 'xrfiddsyiq.png',
 'E99D37DA-8254-4004-A0B7-6FB6500FA2D2',
 'iudbcryhic.png',
 'havvtevemq.png',
 'D2DE592A-E06B-4585-8530-DDDCD2C0A557',
 '7032A51F-7CA2-4563-84FC-BBB586F29C2E',
 '3A1B2CF3-8E26-4A8F-98F9-A5A201F59C02',
 'A1D7E431-F3F7-40AF-8AE0-ACD88BCE00B4',
 'E72F40BF-4D8B-4173-A941-639124AFA48C',
 'ddbkcwzduk.png',
 '5B628C0D-D773-4FCB-97CE-8B47E2095417',
 'dgryerixvm.png',
 'A2BDC3D8-2424-437A-A9C4-1E729C99B696',
 '5752D0CA-0C51-4843-BF6A-043F1B495C21',
 'tcjopuppma.png',
 'rbkmmpcswm.png',
 'E070B4CA-A725-4A3E-98CB-27977962ADAA',
 'A2EA00FA-5B5F-4400-B02E-7379B485203F',
 '3C647D6A-9DAA-4BD0-9074-0219244E7248',
 'csahpvpsho.png',
 'F5EB94E6-A48D-4385-B420-84B728A37AC7',
 'wbcvxqgqjl.png',
 'mnkypniesf.png',
 '2356B4F2-BDCD-47EF-A9AF-8CBC9C26F823',
 'yqcgxnqyxh.png',
 '0A1CBD87-8558-4FD7-B7B7-8BD45BED4B51',
 '4C8ECEF5-F426-45A1-9CD0-E60E814813FC',
 '585E03A0-3140-47E6-8AF2-80AE334C72FE',
 '42506BBE-A15E-4053-8BFC-41097FD53E81',
 '66EBE924-62BD-4180-AFE2-4FB6580AD8FF',
 'dlsjugrzna.png',
 'sxegfrjyqs.png',
 '3B6A0EE9-EDEE-40D0-A946-DF6ACC54DA15',
 '8D01C331-5F1B-4CF7-97B9-10842D2B6D80',
 '5D5AB2D7-A009-4643-9D6D-832C7DEEA060',
 'chfnbxfkzt.png',
 'yactizfjjm.png',
 '671A0434-5947-4CBB-BD38-57D300B4DABA',
 'EC50A76A-4635-4120-996D-5B819AE681D5',
 '2C78BF3A-9391-485D-A1A9-3B75133CEF70',
 'aoudycbjto.png',
 '60D35D2A-CD62-430C-B158-672850343F2D',
 '95BB8102-38C4-4176-8C59-4641D94B251B',
 'pantvsbmlj.png',
 'juhcnnqolv.png',
 '1FAE048B-5096-41C8-8913-06B24CA704EF',
 'odmracornb.png',
 'incbegrhny.png',
 'ucsfkgpfnx.png',
 'wmjeqtowpq.png',
 'peeqmirtfg.png',
 '01B7BBE7-3088-4EF3-8BEB-2747E61AF85B',
 'utwabexwvm.png',
 'jxzmbupowr.png',
 'ecehmvldcv.png',
 'ivrniuerqf.png',
 '2B85BAE1-EF41-45B4-88A4-D29F052B5650',
 '898B95B4-9020-47D5-A70C-F38F03B6BC87',
 'cvjxhzkgzt.png',
 'xgqfyhtwgv.png',
 'AAB9658A-E6B4-486D-ABCE-020AFB941B90',
 'uhlslgvwst.png',
 'fwdfnzyvfh.png',
 'glowgcyfkb.png',
 'dygcvsvjcy.png',
 'EEF1BC24-8FF8-4D7A-B528-DBEFCFEF5CD1',
 '3387FCC1-5C4E-4031-9093-6151D993A491',
 '094AEB05-C4F6-4860-9A28-C8D263F86BBD',
 'opamopbvif.png',
 'F3D8FD5B-F2D1-43A1-8CB9-670CCB2B6E80',
 'yjdmnrzncb.png',
 'nudjzivpzl.png',
 'CD874EE4-BE09-46B9-8000-F41D40C0E78B',
 'tcfsosoctl.png',
 'cepajzugwb.png',

In [15]:
alldb3['RowKey'] = alldb2['RowKey'].astype('string')  #เปลี่ยนชนิดข้อมูลโดยใช้ astype
alldb3

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,user,RowKey,date,ov,phone,site,time,urine,PartitionKey
185,85879,shmpdrmtgc.png,2022-03-24,0,OPPO CPH2293,05194,13:08:39,มีตะกอน,0000
188,27529,ADC54E82-4225-4DE6-89A6-A7E556C15FB1,2022-02-25,0,"iPhone13,1",04999,14:22:22,ปกติ (เหลืองใส),0000
190,06223,kfpwuaqldj.png,2022-03-23,0,Xiaomi 21081111RG,13777,16:31:45,ปกติ (เหลืองใส),00000
191,12015,00859DB9-1BD9-4825-B246-3DC25EFD1924,2022-03-30,4,"iPhone12,3",06307,14:46:08,ปกติ (เหลืองใส),00001
192,91811,1376ACA2-AFA5-4457-967A-D2FCF908E6A5,2022-03-30,4,"iPhone14,3",05328,15:27:45,ปกติ (เหลืองใส),00001
...,...,...,...,...,...,...,...,...,...
39812,99999,F45E78D3-7D89-47A3-8207-C705377E0E0A,2022-03-11,1,"iPhone14,2",99999,11:36:34,ขุ่น,99999
39813,99999,lnlohgqckf.png,2022-03-10,0,Samsung SM-G998B,99999,18:10:29,มีตะกอน,99999
39814,99999,vkdocpmjiv.png,2022-03-10,1,Samsung SM-G998B,99999,12:14:41,"ขุ่น, มีเม็ดเลือดแดง",99999
39815,99999,vrvyfnvayq.png,2022-03-10,1,Samsung SM-G998B,99999,13:58:01,ปกติ (เหลืองใส),99999
39816,99999,zuhbtvyrce.png,2022-03-10,1,Samsung SM-G998B,99999,13:57:58,ปกติ (เหลืองใส),99999

In [17]:
print(alldb3.dtypes)  #เชคชนิดข้อมูล RowKey เปลี่ยนเป็น  string แล้ว

user            object
RowKey          string
date            object
ov              object
phone           object
site            object
time            object
urine           object
PartitionKey    object
dtype: object

###date เป็น YYYY-MM-DD

In [18]:
set(alldb3['date'])  #ดูข้อมูลในคอลัมน์ date

{'2022-02-15',
 '2022-02-17',
 '2022-02-18',
 '2022-02-19',
 '2022-02-21',
 '2022-02-22',
 '2022-02-23',
 '2022-02-24',
 '2022-02-25',
 '2022-02-26',
 '2022-02-27',
 '2022-02-28',
 '2022-03-01',
 '2022-03-02',
 '2022-03-03',
 '2022-03-04',
 '2022-03-05',
 '2022-03-06',
 '2022-03-07',
 '2022-03-08',
 '2022-03-09',
 '2022-03-10',
 '2022-03-11',
 '2022-03-12',
 '2022-03-13',
 '2022-03-14',
 '2022-03-15',
 '2022-03-16',
 '2022-03-17',
 '2022-03-18',
 '2022-03-19',
 '2022-03-20',
 '2022-03-21',
 '2022-03-22',
 '2022-03-23',
 '2022-03-24',
 '2022-03-25',
 '2022-03-26',
 '2022-03-27',
 '2022-03-28',
 '2022-03-29',
 '2022-03-30',
 '2022-03-31',
 '2022-04-01',
 '2022-04-02',
 '2022-04-03',
 '2022-04-04',
 '2022-04-05'}

In [19]:
alldb3['date'] = alldb3['date'].replace(':','-', regex=True)  #แทนที่ : ด้วย - เพื่อให้เป็นตามข้อกำหนด
alldb3

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,user,RowKey,date,ov,phone,site,time,urine,PartitionKey
185,85879,shmpdrmtgc.png,2022-03-24,0,OPPO CPH2293,05194,13:08:39,มีตะกอน,0000
188,27529,ADC54E82-4225-4DE6-89A6-A7E556C15FB1,2022-02-25,0,"iPhone13,1",04999,14:22:22,ปกติ (เหลืองใส),0000
190,06223,kfpwuaqldj.png,2022-03-23,0,Xiaomi 21081111RG,13777,16:31:45,ปกติ (เหลืองใส),00000
191,12015,00859DB9-1BD9-4825-B246-3DC25EFD1924,2022-03-30,4,"iPhone12,3",06307,14:46:08,ปกติ (เหลืองใส),00001
192,91811,1376ACA2-AFA5-4457-967A-D2FCF908E6A5,2022-03-30,4,"iPhone14,3",05328,15:27:45,ปกติ (เหลืองใส),00001
...,...,...,...,...,...,...,...,...,...
39812,99999,F45E78D3-7D89-47A3-8207-C705377E0E0A,2022-03-11,1,"iPhone14,2",99999,11:36:34,ขุ่น,99999
39813,99999,lnlohgqckf.png,2022-03-10,0,Samsung SM-G998B,99999,18:10:29,มีตะกอน,99999
39814,99999,vkdocpmjiv.png,2022-03-10,1,Samsung SM-G998B,99999,12:14:41,"ขุ่น, มีเม็ดเลือดแดง",99999
39815,99999,vrvyfnvayq.png,2022-03-10,1,Samsung SM-G998B,99999,13:58:01,ปกติ (เหลืองใส),99999
39816,99999,zuhbtvyrce.png,2022-03-10,1,Samsung SM-G998B,99999,13:57:58,ปกติ (เหลืองใส),99999

###phone เป็น String

In [20]:
set(alldb3['phone']) #ดูค่าข้อมูลในคอลัมน์ phone

{'HUAWEI CLT-L29',
 'HUAWEI ELE-L29',
 'HUAWEI FLA-LX2',
 'HUAWEI JAT-L29',
 'HUAWEI JKM-LX2',
 'HUAWEI LDN-LX2',
 'HUAWEI LYA-L29',
 'HUAWEI MAR-AL00',
 'HUAWEI MRD-LX1',
 'HUAWEI PPA-LX2',
 'HUAWEI SHT-AL09',
 'HUAWEI STK-L22',
 'HUAWEI VOG-L29',
 'HUAWEI YAL-L21',
 'INFINIX MOBILITY LIMITED Infinix X657B',
 'INFINIX MOBILITY LIMITED Infinix X657C',
 'INFINIX MOBILITY LIMITED Infinix X688C',
 'INFINIX MOBILITY LIMITED Infinix X698',
 'LAVA LH9930',
 'OPPO A1601',
 'OPPO A37f',
 'OPPO A37fw',
 'OPPO CPH1819',
 'OPPO CPH1821',
 'OPPO CPH1823',
 'OPPO CPH1907',
 'OPPO CPH1911',
 'OPPO CPH1931',
 'OPPO CPH1933',
 'OPPO CPH1937',
 'OPPO CPH1969',
 'OPPO CPH1989',
 'OPPO CPH2001',
 'OPPO CPH2015',
 'OPPO CPH2065',
 'OPPO CPH2083',
 'OPPO CPH2113',
 'OPPO CPH2121',
 'OPPO CPH2127',
 'OPPO CPH2145',
 'OPPO CPH2159',
 'OPPO CPH2185',
 'OPPO CPH2197',
 'OPPO CPH2203',
 'OPPO CPH2219',
 'OPPO CPH2237',
 'OPPO CPH2239',
 'OPPO CPH2269',
 'OPPO CPH2293',
 'OPPO CPH2343',
 'Realme RMX1851',
 'Realme RMX1911',
 'Realme RMX1941',
 'Realme RMX1971',
 'Realme RMX2001',
 'Realme RMX2030',
 'Realme RMX2040',
 'Realme RMX2061',
 'Realme RMX2111',
 'Realme RMX2170',
 'Realme RMX3085',
 'Realme RMX3191',
 'Realme RMX3231',
 'Realme RMX3241',
 'Samsung SM-A022F',
 'Samsung SM-A025F',
 'Samsung SM-A035F',
 'Samsung SM-A037F',
 'Samsung SM-A105G',
 'Samsung SM-A107F',
 'Samsung SM-A115F',
 'Samsung SM-A125F',
 'Samsung SM-A127F',
 'Samsung SM-A205F',
 'Samsung SM-A207F',
 'Samsung SM-A217F',
 'Samsung SM-A226B',
 'Samsung SM-A305F',
 'Samsung SM-A307GN',
 'Samsung SM-A315G',
 'Samsung SM-A326B',
 'Samsung SM-A426B',
 'Samsung SM-A505F',
 'Samsung SM-A507FN',
 'Samsung SM-A515F',
 'Samsung SM-A525F',
 'Samsung SM-A526B',
 'Samsung SM-A528B',
 'Samsung SM-A530F',
 'Samsung SM-A605G',
 'Samsung SM-A705F',
 'Samsung SM-A715F',
 'Samsung SM-A730F',
 'Samsung SM-A750GN',
 'Samsung SM-A805F',
 'Samsung SM-G780F',
 'Samsung SM-G781B',
 'Samsung SM-G955F',
 'Samsung SM-G965F',
 'Samsung SM-G965U',
 'Samsung SM-G973F',
 'Samsung SM-G985F',
 'Samsung SM-G991B',
 'Samsung SM-G998B',
 'Samsung SM-J400F',
 'Samsung SM-J415F',
 'Samsung SM-J610F',
 'Samsung SM-M022F',
 'Samsung SM-M315F',
 'Samsung SM-N770F',
 'Samsung SM-N950F',
 'Samsung SM-N960F',
 'Samsung SM-N970F',
 'Samsung SM-N975F',
 'Samsung SM-P610',
 'Samsung SM-S908E',
 'Samsung SM-T295',
 'Samsung SM-T500',
 'Vivo 1806',
 'Vivo 1818',
 'Vivo 1819',
 'Vivo 1820',
 'Vivo 1901',
 'Vivo 1902',
 'Vivo 1904',
 'Vivo 1906',
 'Vivo 1915',
 'Vivo 1920',
 'Vivo 1933',
 'Vivo 1935',
 'Vivo 1938',
 'Vivo 2006',
 'Vivo 2015',
 'Vivo 2018',
 'Vivo V2025',
 'Vivo V2026',
 'Vivo V2027',
 'Vivo V2036',
 'Vivo V2038',
 'Vivo V2041',
 'Vivo V2043',
 'Vivo V2050',
 'Vivo V2102',
 'Vivo V2109',
 'Vivo V2111',
 'Vivo V2124',
 'Vivo V2126',
 'Vivo V2130',
 'Vivo V2131',
 'WIKO W-K211-TH',
 'Xiaomi 21061110AG',
 'Xiaomi 21061119AG',
 'Xiaomi 2107113SG',
 'Xiaomi 21081111RG',
 'Xiaomi 2109119DG',
 'Xiaomi M2003J15SC',
 'Xiaomi M2004J19C',
 'Xiaomi M2006C3LG',
 'Xiaomi M2007J3SY',
 'Xiaomi M2010J19SG',
 'Xiaomi M2012K11AG',
 'Xiaomi M2101K9AG',
 'Xiaomi M2102J20SG',
 'Xiaomi MI 8',
 'Xiaomi Redmi 8A',
 'Xiaomi Redmi Note 9S',
 'iPad11,4',
 'iPad11,6',
 'iPad11,7',
 'iPad12,1',
 'iPad13,1',
 'iPad13,2',
 'iPad13,4',
 'iPad13,6',
 'iPad14,2',
 'iPad7,11',
 'iPad7,12',
 'iPad7,4',
 'iPad7,5',
 'iPhone10,2',
 'iPhone10,3',
 'iPhone10,4',
 'iPhone10,5',
 'iPhone10,6',
 'iPhone11,2',
 'iPhone11,6',
 'iPhone11,8',
 'iPhone12,1',
 'iPhone12,3',
 'iPhone12,5',
 'iPhone12,8',
 'iPhone13',
 'iPhone13,1',
 'iPhone13,2',
 'iPhone13,3',
 'iPhone13,4',
 'iPhone14,2',
 'iPhone14,3',
 'iPhone14,5',
 'iPhone8,1',
 'iPhone8,2',
 'iPhone9,1',
 'iPhone9,2',
 'iPhone9,3',
 'iPhone9,4'}

In [21]:
alldb3['phone'] = alldb3['phone'].astype('string')  #เปลี่ยนชนิดข้อมูลโดยใช้ astype
alldb3

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,user,RowKey,date,ov,phone,site,time,urine,PartitionKey
185,85879,shmpdrmtgc.png,2022-03-24,0,OPPO CPH2293,05194,13:08:39,มีตะกอน,0000
188,27529,ADC54E82-4225-4DE6-89A6-A7E556C15FB1,2022-02-25,0,"iPhone13,1",04999,14:22:22,ปกติ (เหลืองใส),0000
190,06223,kfpwuaqldj.png,2022-03-23,0,Xiaomi 21081111RG,13777,16:31:45,ปกติ (เหลืองใส),00000
191,12015,00859DB9-1BD9-4825-B246-3DC25EFD1924,2022-03-30,4,"iPhone12,3",06307,14:46:08,ปกติ (เหลืองใส),00001
192,91811,1376ACA2-AFA5-4457-967A-D2FCF908E6A5,2022-03-30,4,"iPhone14,3",05328,15:27:45,ปกติ (เหลืองใส),00001
...,...,...,...,...,...,...,...,...,...
39812,99999,F45E78D3-7D89-47A3-8207-C705377E0E0A,2022-03-11,1,"iPhone14,2",99999,11:36:34,ขุ่น,99999
39813,99999,lnlohgqckf.png,2022-03-10,0,Samsung SM-G998B,99999,18:10:29,มีตะกอน,99999
39814,99999,vkdocpmjiv.png,2022-03-10,1,Samsung SM-G998B,99999,12:14:41,"ขุ่น, มีเม็ดเลือดแดง",99999
39815,99999,vrvyfnvayq.png,2022-03-10,1,Samsung SM-G998B,99999,13:58:01,ปกติ (เหลืองใส),99999
39816,99999,zuhbtvyrce.png,2022-03-10,1,Samsung SM-G998B,99999,13:57:58,ปกติ (เหลืองใส),99999

###site เป็นตัวเลข 5 หลัก (ตัวเลขเท่านั้น)

In [23]:
alldb4 = alldb3[(alldb3['site'].astype(str).str.isdigit()) & (alldb3['site'].str.len() == 5)]  #เลือกข้อมูลที่เป็นตัวเลข 5 หลักเท่านั้น
alldb4

,user,RowKey,date,ov,phone,site,time,urine,PartitionKey
185,85879,shmpdrmtgc.png,2022-03-24,0,OPPO CPH2293,05194,13:08:39,มีตะกอน,0000
188,27529,ADC54E82-4225-4DE6-89A6-A7E556C15FB1,2022-02-25,0,"iPhone13,1",04999,14:22:22,ปกติ (เหลืองใส),0000
190,06223,kfpwuaqldj.png,2022-03-23,0,Xiaomi 21081111RG,13777,16:31:45,ปกติ (เหลืองใส),00000
191,12015,00859DB9-1BD9-4825-B246-3DC25EFD1924,2022-03-30,4,"iPhone12,3",06307,14:46:08,ปกติ (เหลืองใส),00001
192,91811,1376ACA2-AFA5-4457-967A-D2FCF908E6A5,2022-03-30,4,"iPhone14,3",05328,15:27:45,ปกติ (เหลืองใส),00001
...,...,...,...,...,...,...,...,...,...
39812,99999,F45E78D3-7D89-47A3-8207-C705377E0E0A,2022-03-11,1,"iPhone14,2",99999,11:36:34,ขุ่น,99999
39813,99999,lnlohgqckf.png,2022-03-10,0,Samsung SM-G998B,99999,18:10:29,มีตะกอน,99999
39814,99999,vkdocpmjiv.png,2022-03-10,1,Samsung SM-G998B,99999,12:14:41,"ขุ่น, มีเม็ดเลือดแดง",99999
39815,99999,vrvyfnvayq.png,2022-03-10,1,Samsung SM-G998B,99999,13:58:01,ปกติ (เหลืองใส),99999
39816,99999,zuhbtvyrce.png,2022-03-10,1,Samsung SM-G998B,99999,13:57:58,ปกติ (เหลืองใส),99999

###time เป็น hh-mm-ss

In [24]:
set(alldb4['time'])  #ดูข้อมูลในคอลัมน์ time

{'14:55:37',
 '12:27:45',
 '13:49:29',
 '16:21:36',
 '12:24:00',
 '15:06:12',
 '13:51:46',
 '10:10:10',
 '11:40:35',
 '13:58:00',
 '10:06:10',
 '18:01:57',
 '10:37:50',
 '09:04:02',
 '18:26:55',
 '15:48:06',
 '18:46:28',
 '10:12:30',
 '15:31:57',
 '09:36:45',
 '12:53:38',
 '12:38:17',
 '15:08:47',
 '12:13:06',
 '21:13:55',
 '11:59:17',
 '11:39:09',
 '11:40:21',
 '11:23:11',
 '15:38:43',
 '11:48:19',
 '11:03:52',
 '18:10:29',
 '09:31:03',
 '14:00:55',
 '16:10:28',
 '12:12:28',
 '11:37:27',
 '11:05:02',
 '09:03:27',
 '12:48:04',
 '11:19:02',
 '17:29:31',
 '10:31:37',
 '11:24:51',
 '09:39:20',
 '14:44:18',
 '09:42:30',
 '09:42:34',
 '17:11:51',
 '10:48:27',
 '19:28:32',
 '13:17:19',
 '12:07:54',
 '16:06:05',
 '12:26:00',
 '11:10:21',
 '16:25:27',
 '12:34:05',
 '09:23:53',
 '16:38:10',
 '21:08:10',
 '15:04:24',
 '14:44:06',
 '09:42:49',
 '14:46:13',
 '09:42:01',
 '08:21:43',
 '09:28:26',
 '13:40:59',
 '10:01:13',
 '08:57:33',
 '09:02:45',
 '16:14:57',
 '13:50:01',
 '10:58:45',
 '12:16:55',
 '16:19:58',
 '12:04:15',
 '19:55:57',
 '15:13:38',
 '14:39:18',
 '17:20:58',
 '13:46:26',
 '16:27:07',
 '11:55:43',
 '11:25:16',
 '11:23:39',
 '10:50:24',
 '11:39:48',
 '09:55:21',
 '16:32:34',
 '11:42:19',
 '20:26:30',
 '10:51:18',
 '16:40:01',
 '09:23:27',
 '11:06:14',
 '14:28:54',
 '15:00:15',
 '09:55:52',
 '12:04:02',
 '09:51:33',
 '12:01:33',
 '10:05:23',
 '11:31:37',
 '16:17:06',
 '16:27:37',
 '14:04:38',
 '11:19:56',
 '13:12:09',
 '16:02:53',
 '11:38:51',
 '11:01:36',
 '11:44:45',
 '12:13:34',
 '12:27:42',
 '13:38:19',
 '12:58:21',
 '12:11:50',
 '10:38:08',
 '11:15:54',
 '12:46:20',
 '10:06:32',
 '10:52:35',
 '14:57:07',
 '16:06:43',
 '10:42:49',
 '10:44:40',
 '15:12:03',
 '14:56:42',
 '10:41:16',
 '21:14:59',
 '17:20:33',
 '13:57:38',
 '15:25:41',
 '11:27:01',
 '10:44:51',
 '21:21:00',
 '10:51:26',
 '10:22:54',
 '11:23:36',
 '11:38:01',
 '10:15:34',
 '11:38:42',
 '11:46:14',
 '10:04:33',
 '10:55:47',
 '11:45:53',
 '09:55:58',
 '14:02:34',
 '14:11:34',
 '15:12:16',
 '12:15:14',
 '15:36:50',
 '19:33:08',
 '09:32:23',
 '09:23:09',
 '16:38:18',
 '10:39:53',
 '09:54:33',
 '10:59:44',
 '16:52:13',
 '13:31:48',
 '12:30:59',
 '16:22:46',
 '13:59:13',
 '11:10:40',
 '13:14:35',
 '15:16:13',
 '14:16:33',
 '12:45:39',
 '16:19:11',
 '11:38:40',
 '13:05:59',
 '19:35:46',
 '10:36:42',
 '15:29:11',
 '10:20:56',
 '12:13:24',
 '11:20:43',
 '10:15:45',
 '13:36:25',
 '13:00:31',
 '13:44:29',
 '12:05:16',
 '11:26:04',
 '11:09:05',
 '14:56:11',
 '12:24:44',
 '13:01:07',
 '10:09:47',
 '16:53:33',
 '11:56:44',
 '13:12:43',
 '11:30:20',
 '15:09:28',
 '13:24:08',
 '11:18:49',
 '13:11:03',
 '11:22:38',
 '14:55:56',
 '21:16:32',
 '10:36:58',
 '15:47:25',
 '09:47:05',
 '20:54:34',
 '08:42:49',
 '13:04:27',
 '10:10:08',
 '12:29:43',
 '15:42:22',
 '09:52:36',
 '11:52:00',
 '13:20:33',
 '12:47:34',
 '14:29:09',
 '11:45:17',
 '14:15:53',
 '12:08:03',
 '12:14:01',
 '15:36:14',
 '08:47:56',
 '13:28:38',
 '12:59:19',
 '10:05:56',
 '12:34:03',
 '15:32:47',
 '14:48:22',
 '14:19:54',
 '10:07:05',
 '10:01:14',
 '11:50:30',
 '12:56:07',
 '12:09:05',
 '10:05:18',
 '15:00:59',
 '15:33:20',
 '14:53:48',
 '15:32:06',
 '09:51:45',
 '13:56:34',
 '12:35:48',
 '11:23:25',
 '12:42:07',
 '12:11:43',
 '15:02:39',
 '20:31:54',
 '11:24:18',
 '11:37:38',
 '12:22:40',
 '16:29:53',
 '16:02:49',
 '17:23:37',
 '10:46:43',
 '14:58:04',
 '15:30:39',
 '15:34:31',
 '14:42:04',
 '10:51:11',
 '12:49:24',
 '09:32:12',
 '10:09:56',
 '11:47:41',
 '10:36:13',
 '14:06:41',
 '12:16:20',
 '15:23:45',
 '18:32:19',
 '16:09:55',
 '09:42:29',
 '14:37:34',
 '13:42:11',
 '14:42:18',
 '13:57:28',
 '15:04:48',
 '15:08:33',
 '16:42:19',
 '12:52:41',
 '08:39:50',
 '19:48:26',
 '15:43:29',
 '12:37:17',
 '13:33:20',
 '16:23:11',
 '15:24:03',
 '11:15:37',
 '10:02:19',
 '14:10:01',
 '15:35:30',
 '11:36:14',
 '11:45:10',
 '10:47:08',
 '09:17:43',
 '10:15:42',
 '10:33:15',
 '10:56:08',
 '09:07:05',
 '21:18:30',
 '19:06:50',
 '12:57:08',
 '12:01:56',
 '15:55:35',
 '16:59:17',
 '15:20:53',
 '10:00:00',
 '19:01:11',
 '15:28:06',
 '11:57:16',
 '11:30:05',
 '12:17:55',
 '11:25:27',
 '16:43:38',
 '12:13:30',
 '10:18:33',
 '16:41:14',
 '10:56:55',
 '16:13:36',
 '23:20:10',
 '12:41:45',
 '09:06:47',
 '16:23:01',
 '11:13:01',
 '13:45:33',
 '17:22:25',
 '17:15:52',
 '11:40:07',
 '09:58:13',
 '09:48:30',
 '16:51:34',
 '11:31:16',
 '13:31:19',
 '09:51:58',
 '13:52:06',
 '14:17:46',
 '15:16:20',
 '09:49:34',
 '11:48:03',
 '11:28:19',
 '13:36:23',
 '15:20:12',
 '15:09:46',
 '19:21:37',
 '14:44:11',
 '15:47:36',
 '16:14:47',
 '09:34:28',
 '15:40:41',
 '16:54:19',
 '09:30:27',
 '10:01:29',
 '09:34:45',
 '12:13:47',
 '10:39:07',
 '11:45:52',
 '12:14:14',
 '13:08:50',
 '15:38:11',
 '13:38:32',
 '09:01:09',
 '19:28:03',
 '10:07:15',
 '12:31:32',
 '10:36:09',
 '17:52:25',
 '10:14:55',
 '16:31:16',
 '09:56:56',
 '12:09:32',
 '07:02:58',
 '10:32:16',
 '15:50:59',
 '11:11:31',
 '14:03:50',
 '14:05:58',
 '12:30:13',
 '12:41:04',
 '13:39:01',
 '12:06:11',
 '12:07:45',
 '13:21:20',
 '15:19:37',
 '23:29:47',
 '13:29:22',
 '10:00:41',
 '16:19:14',
 '12:51:47',
 '12:39:09',
 '10:11:28',
 '10:15:06',
 '09:21:07',
 '09:11:04',
 '16:05:29',
 '09:40:34',
 '12:48:30',
 '10:59:19',
 '15:55:47',
 '14:58:00',
 '15:56:21',
 '15:05:43',
 '13:50:24',
 '14:43:19',
 '11:39:07',
 '18:24:15',
 '17:23:43',
 '16:26:12',
 '16:54:12',
 '15:07:22',
 '10:42:56',
 '18:26:03',
 '12:23:11',
 '12:16:05',
 '09:10:13',
 '15:38:51',
 '10:56:23',
 '10:24:59',
 '15:38:20',
 '12:16:54',
 '11:30:45',
 '15:36:07',
 '09:41:03',
 '13:49:19',
 '19:08:59',
 '11:57:22',
 '17:07:48',
 '09:45:54',
 '13:49:54',
 '12:16:39',
 '14:13:54',
 '14:08:36',
 '18:43:41',
 '12:52:11',
 '14:24:08',
 '17:21:45',
 '11:08:54',
 '10:59:34',
 '09:08:23',
 '10:36:00',
 '10:45:05',
 '12:13:45',
 '11:17:10',
 '14:38:12',
 '07:27:41',
 '15:44:35',
 '11:47:21',
 '11:17:13',
 '12:57:43',
 '15:20:10',
 '12:00:53',
 '20:20:56',
 '09:36:47',
 '10:44:26',
 '17:55:13',
 '14:37:10',
 '18:32:15',
 '11:35:27',
 '10:23:45',
 '10:09:31',
 '10:12:45',
 '12:30:31',
 '10:39:43',
 '11:00:37',
 '08:55:34',
 '13:41:33',
 '13:50:32',
 '15:55:41',
 '14:43:30',
 '17:07:33',
 '14:41:55',
 '08:10:09',
 '10:12:28',
 '12:21:20',
 '10:24:05',
 '10:56:48',
 '14:38:24',
 '17:44:07',
 '11:26:23',
 '15:17:40',
 '10:20:07',
 '11:58:03',
 '15:15:39',
 '11:30:49',
 '12:16:03',
 '09:30:14',
 '09:59:15',
 '11:21:42',
 '10:24:24',
 '11:45:25',
 '17:47:21',
 '14:32:55',
 '11:50:58',
 '09:45:28',
 '14:14:58',
 '21:50:17',
 '10:09:37',
 '14:03:08',
 '09:46:06',
 '13:20:06',
 '11:25:58',
 '09:30:03',
 '14:32:30',
 '10:39:49',
 '11:44:57',
 '11:34:57',
 '09:30:30',
 '15:55:16',
 '11:09:16',
 '14:14:35',
 '09:20:10',
 '15:15:06',
 '09:25:41',
 '11:45:04',
 '19:56:26',
 '09:40:35',
 '11:06:34',
 '10:35:45',
 '12:48:58',
 '09:28:06',
 '13:08:25',
 '09:56:02',
 '17:44:42',
 '11:06:36',
 '08:47:09',
 '15:56:33',
 '15:52:55',
 '11:14:31',
 '10:12:57',
 '13:23:37',
 '10:58:12',
 '11:42:46',
 '16:14:35',
 '16:06:34',
 '14:30:36',
 '10:38:20',
 '11:25:30',
 '10:43:33',
 '11:33:42',
 '10:59:47',
 '14:49:20',
 '11:26:56',
 '11:15:05',
 '11:09:51',
 '10:07:24',
 '17:47:43',
 '17:26:08',
 '10:54:53',
 '14:08:13',
 '12:03:16',
 '11:48:16',
 '11:53:33',
 '16:50:08',
 '16:48:05',
 '10:55:58',
 '10:32:06',
 '21:49:46',
 '16:53:24',
 '12:46:39',
 '13:12:16',
 '13:34:55',
 '13:35:03',
 '15:09:06',
 '12:19:54',
 '12:52:42',
 '09:16:00',
 '11:44:06',
 '15:14:29',
 '10:17:26',
 '09:51:42',
 '12:39:10',
 '15:15:28',
 '12:01:58',
 '11:26:54',
 '11:21:33',
 '15:49:59',
 '09:26:21',
 '14:08:32',
 '12:57:21',
 '10:54:43',
 '11:20:45',
 '17:48:39',
 '16:10:56',
 '10:30:39',
 '22:17:35',
 '10:43:52',
 '09:40:48',
 '11:42:11',
 '11:04:17',
 '12:11:05',
 '10:46:53',
 '11:12:06',
 '11:09:50',
 '11:51:42',
 '16:54:10',
 '14:23:34',
 '12:28:02',
 '11:17:56',
 '09:23:31',
 '11:35:44',
 '15:12:20',
 '09:52:15',
 '11:58:52',
 '07:36:22',
 '13:52:12',
 '12:56:48',
 '14:43:01',
 '12:12:29',
 '11:05:15',
 '19:24:57',
 '18:34:11',
 '11:30:11',
 '15:14:03',
 '16:23:28',
 '12:32:51',
 '11:29:53',
 '15:04:40',
 '15:32:53',
 '10:57:47',
 '14:46:24',
 '12:12:36',
 '21:56:44',
 '10:04:30',
 '09:26:55',
 '14:31:51',
 '09:16:13',
 '09:55:11',
 '14:45:29',
 '11:22:04',
 '10:23:07',
 '11:30:48',
 '11:01:31',
 '11:20:39',
 '11:41:38',
 '10:10:48',
 '10:51:43',
 '11:09:08',
 '14:47:53',
 '18:13:27',
 '11:14:27',
 '10:48:28',
 '15:11:19',
 '11:37:49',
 '12:09:20',
 '11:45:12',
 '12:12:17',
 '11:53:55',
 '13:08:53',
 '09:54:42',
 '10:40:51',
 '10:21:06',
 '15:38:29',
 '11:00:36',
 '09:54:04',
 '15:21:57',
 '14:35:20',
 '14:14:33',
 '16:47:39',
 '14:55:20',
 '14:11:54',
 '09:53:06',
 '09:58:07',
 '22:41:08',
 '09:20:35',
 '16:33:13',
 '10:03:11',
 '09:58:04',
 '15:02:04',
 '15:40:11',
 '16:09:27',
 '11:18:42',
 '12:18:46',
 '12:14:20',
 '16:04:10',
 '11:18:29',
 '10:47:29',
 '11:28:09',
 '14:16:00',
 '10:15:30',
 '16:00:46',
 '10:01:33',
 '11:36:57',
 '14:34:13',
 '10:30:30',
 '13:26:19',
 '15:27:15',
 '09:19:51',
 '16:43:13',
 '15:31:17',
 '14:47:12',
 '09:58:28',
 '12:28:06',
 '11:08:56',
 '09:40:28',
 '17:04:15',
 '12:47:49',
 '10:01:45',
 '09:11:08',
 '11:15:59',
 '17:20:07',
 '15:30:59',
 '11:46:42',
 '14:19:28',
 '08:48:20',
 '14:51:08',
 '11:44:42',
 '17:39:18',
 '10:49:27',
 '09:32:07',
 '13:44:45',
 '09:46:12',
 '10:19:49',
 '11:27:43',
 '11:42:20',
 '13:47:00',
 '13:48:46',
 '15:52:21',
 '09:45:37',
 '12:14:55',
 '18:12:18',
 '11:48:28',
 '07:26:45',
 '14:23:16',
 '18:28:24',
 '10:09:49',
 '14:50:59',
 '10:18:15',
 '14:42:02',
 '10:10:37',
 '13:58:24',
 '16:52:00',
 '10:37:29',
 '11:02:17',
 '11:07:57',
 '11:04:03',
 '11:18:13',
 '13:32:56',
 '14:06:50',
 '10:47:25',
 '13:18:16',
 '11:50:31',
 '09:01:15',
 '14:06:12',
 '12:00:27',
 '13:52:32',
 '14:24:50',
 '09:25:31',
 '15:49:08',
 '09:55:34',
 '10:38:44',
 '12:56:02',
 '18:41:21',
 '11:46:32',
 '09:09:26',
 '16:26:03',
 '13:07:46',
 '14:58:18',
 '11:09:33',
 '15:09:36',
 '09:34:54',
 '10:12:11',
 '12:01:01',
 '17:38:21',
 '13:02:38',
 '10:09:17',
 '11:10:22',
 '15:05:28',
 '10:30:29',
 '10:07:37',
 '15:42:14',
 '11:21:05',
 '15:11:49',
 '17:18:16',
 '13:10:59',
 '20:27:58',
 '10:04:10',
 '14:51:29',
 '16:58:37',
 '10:16:47',
 '14:35:10',
 '14:52:06',
 '11:33:56',
 '10:35:01',
 '09:51:00',
 '16:21:52',
 '10:26:21',
 '16:37:46',
 '20:30:07',
 '10:35:02',
 '18:45:03',
 '12:40:25',
 '13:58:29',
 '14:23:42',
 '14:45:21',
 '10:14:38',
 '17:01:34',
 '11:24:02',
 '20:31:51',
 '10:46:46',
 '14:35:27',
 '12:01:30',
 '13:19:17',
 '19:22:36',
 '11:27:36',
 '10:18:26',
 '10:19:32',
 '16:46:02',
 '12:03:19',
 '12:24:13',
 '11:57:04',
 '14:26:44',
 '10:31:48',
 '18:39:00',
 '17:22:59',
 '15:31:01',
 '10:17:30',
 '09:58:17',
 '10:56:56',
 '12:38:08',
 '16:07:47',
 '21:53:18',
 '09:09:56',
 '11:18:21',
 '15:45:31',
 '16:42:29',
 '13:25:42',
 '15:54:47',
 '15:49:15',
 '17:41:17',
 '11:49:40',
 '13:48:01',
 '11:51:31',
 '18:02:36',
 '11:22:19',
 '14:37:19',
 '11:35:50',
 '16:37:17',
 '09:04:48',
 '15:00:04',
 '12:17:14',
 '19:57:24',
 '11:30:36',
 '12:18:00',
 '17:10:06',
 '16:42:05',
 '12:03:20',
 '11:00:25',
 '13:08:03',
 '17:51:30',
 '14:44:51',
 '11:13:28',
 '12:18:05',
 '10:49:45',
 '10:40:00',
 '13:07:55',
 '10:35:21',
 '14:09:40',
 '11:34:42',
 '11:11:49',
 '09:36:09',
 '15:21:11',
 '13:32:25',
 '16:45:55',
 '15:24:22',
 '14:05:16',
 '17:22:53',
 '14:20:42',
 '09:27:24',
 '17:13:13',
 '10:42:00',
 '11:11:42',
 '16:28:39',
 '16:49:06',
 '11:20:26',
 '10:46:34',
 '10:58:46',
 '12:29:42',
 '11:57:52',
 '11:29:29',
 '10:13:22',
 '16:40:29',
 '11:09:38',
 '15:40:53',
 '09:54:53',
 '14:40:29',
 '12:03:29',
 '11:31:14',
 '11:16:34',
 '12:42:03',
 '09:56:54',
 '09:45:53',
 '11:07:34',
 '20:46:43',
 '13:32:32',
 '15:21:10',
 '10:37:37',
 '15:07:13',
 '18:15:32',
 '14:19:55',
 '14:53:04',
 '17:05:40',
 '10:49:32',
 '10:31:56',
 '17:30:28',
 '11:20:01',
 '11:25:25',
 '09:31:04',
 '16:17:38',
 '18:39:31',
 '12:21:22',
 '20:26:29',
 '12:08:12',
 '10:10:55',
 '16:06:19',
 '16:21:40',
 '17:28:27',
 '11:04:52',
 '11:06:49',
 '13:20:52',
 '08:26:56',
 '12:16:14',
 '10:24:48',
 '16:59:01',
 '20:55:16',
 '10:25:38',
 '12:52:59',
 '15:24:19',
 '14:38:35',
 '15:29:01',
 '14:47:26',
 '13:54:05',
 '17:11:44',
 '09:38:13',
 '11:08:20',
 '11:04:49',
 '10:56:37',
 '15:51:55',
 '11:17:22',
 '11:04:24',
 '15:19:11',
 '17:18:29',
 '10:36:41',
 '19:27:13',
 '10:11:36',
 '15:41:11',
 '17:47:57',
 '13:15:25',
 '22:07:00',
 '10:44:07',
 '14:36:54',
 '09:19:05',
 '10:46:26',
 '14:45:50',
 '14:31:33',
 '17:17:57',
 '15:09:57',
 '12:06:43',
 '14:40:08',
 '09:55:39',
 '17:16:32',
 '13:33:54',
 '10:42:53',
 '13:55:33',
 '10:08:23',
 '09:05:28',
 '16:27:15',
 '14:28:49',
 '20:08:49',
 '11:33:30',
 '11:48:38',
 '14:38:33',
 '10:48:20',
 '12:24:22',
 '10:02:04',
 '10:53:01',
 '11:39:56',
 '11:39:47',
 '15:24:16',
 '16:53:20',
 '11:45:51',
 '16:52:46',
 '17:00:00',
 '10:38:57',
 '10:27:35',
 '12:06:18',
 '11:05:18',
 '16:38:12',
 '12:27:22',
 '17:14:16',
 '15:32:34',
 '09:32:57',
 '12:26:02',
 '15:39:03',
 '19:56:56',
 '09:44:17',
 '21:57:17',
 '10:01:34',
 '10:12:56',
 '09:02:12',
 '17:12:56',
 '16:04:08',
 '09:51:06',
 ...}

In [25]:
alldb4['time'] = alldb4['time'].replace(':','-', regex=True)  #แทนค่า : ด้วย - เพื่อให้เป็นตามข้อกำหนด
alldb4

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,user,RowKey,date,ov,phone,site,time,urine,PartitionKey
185,85879,shmpdrmtgc.png,2022-03-24,0,OPPO CPH2293,05194,13-08-39,มีตะกอน,0000
188,27529,ADC54E82-4225-4DE6-89A6-A7E556C15FB1,2022-02-25,0,"iPhone13,1",04999,14-22-22,ปกติ (เหลืองใส),0000
190,06223,kfpwuaqldj.png,2022-03-23,0,Xiaomi 21081111RG,13777,16-31-45,ปกติ (เหลืองใส),00000
191,12015,00859DB9-1BD9-4825-B246-3DC25EFD1924,2022-03-30,4,"iPhone12,3",06307,14-46-08,ปกติ (เหลืองใส),00001
192,91811,1376ACA2-AFA5-4457-967A-D2FCF908E6A5,2022-03-30,4,"iPhone14,3",05328,15-27-45,ปกติ (เหลืองใส),00001
...,...,...,...,...,...,...,...,...,...
39812,99999,F45E78D3-7D89-47A3-8207-C705377E0E0A,2022-03-11,1,"iPhone14,2",99999,11-36-34,ขุ่น,99999
39813,99999,lnlohgqckf.png,2022-03-10,0,Samsung SM-G998B,99999,18-10-29,มีตะกอน,99999
39814,99999,vkdocpmjiv.png,2022-03-10,1,Samsung SM-G998B,99999,12-14-41,"ขุ่น, มีเม็ดเลือดแดง",99999
39815,99999,vrvyfnvayq.png,2022-03-10,1,Samsung SM-G998B,99999,13-58-01,ปกติ (เหลืองใส),99999
39816,99999,zuhbtvyrce.png,2022-03-10,1,Samsung SM-G998B,99999,13-57-58,ปกติ (เหลืองใส),99999

###urine มีค่า String

In [26]:
alldb4['urine'] = alldb4['urine'].astype('string')  #เปลี่ยนชนิดของข้อมูลให้เป็น string ด้วย astype
alldb4

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,user,RowKey,date,ov,phone,site,time,urine,PartitionKey
185,85879,shmpdrmtgc.png,2022-03-24,0,OPPO CPH2293,05194,13-08-39,มีตะกอน,0000
188,27529,ADC54E82-4225-4DE6-89A6-A7E556C15FB1,2022-02-25,0,"iPhone13,1",04999,14-22-22,ปกติ (เหลืองใส),0000
190,06223,kfpwuaqldj.png,2022-03-23,0,Xiaomi 21081111RG,13777,16-31-45,ปกติ (เหลืองใส),00000
191,12015,00859DB9-1BD9-4825-B246-3DC25EFD1924,2022-03-30,4,"iPhone12,3",06307,14-46-08,ปกติ (เหลืองใส),00001
192,91811,1376ACA2-AFA5-4457-967A-D2FCF908E6A5,2022-03-30,4,"iPhone14,3",05328,15-27-45,ปกติ (เหลืองใส),00001
...,...,...,...,...,...,...,...,...,...
39812,99999,F45E78D3-7D89-47A3-8207-C705377E0E0A,2022-03-11,1,"iPhone14,2",99999,11-36-34,ขุ่น,99999
39813,99999,lnlohgqckf.png,2022-03-10,0,Samsung SM-G998B,99999,18-10-29,มีตะกอน,99999
39814,99999,vkdocpmjiv.png,2022-03-10,1,Samsung SM-G998B,99999,12-14-41,"ขุ่น, มีเม็ดเลือดแดง",99999
39815,99999,vrvyfnvayq.png,2022-03-10,1,Samsung SM-G998B,99999,13-58-01,ปกติ (เหลืองใส),99999
39816,99999,zuhbtvyrce.png,2022-03-10,1,Samsung SM-G998B,99999,13-57-58,ปกติ (เหลืองใส),99999

In [27]:
print(alldb4.dtypes)  #เชคชนิดข้อมูลพบว่าเป็น string แล้ว

user            object
RowKey          string
date            object
ov              object
phone           string
site            object
time            object
urine           string
PartitionKey    object
dtype: object

###ov เป็นตัวเลข มีค่าตั้งแต่ 0-4 (0 คือไม่พบโรค 1-4 คือพบโรคที่ระดับความรุนแรงต่างๆ)
โดยจะกำหนดให้แทนด้วยตัวเลขดังต่อไปนี้ 
* 0 = ไม่พบโรค
* 1 = พบโรคที่ระดับความรุนแรง 1
* 2 = พบโรคที่ระดับความรุนแรง 2
* 3 = พบโรคที่ระดับความรุนแรง 3
* 4 = พบโรคที่ระดับความรุนแรง 4
* ติดเชื้อ +2 = พบโรคที่ระดับความรุนแรง 4

In [35]:
set(alldb4['ov'])  #ดูข้อมูลคอลัมน์ ov

{'ติดเชื้อ +2 ',
 'พบโรคที่ระดับความรุนแรง 1',
 'พบโรคที่ระดับความรุนแรง 2',
 'พบโรคที่ระดับความรุนแรง 3',
 'พบโรคที่ระดับความรุนแรง 4',
 'ไม่พบโรค'}

In [38]:
alldb4['ov'].replace({'0':'ไม่พบโรค',
'1':'พบโรคที่ระดับความรุนแรง 1',
'2':'พบโรคที่ระดับความรุนแรง 2',
'3':'พบโรคที่ระดับความรุนแรง 3',
'4':'พบโรคที่ระดับความรุนแรง 4',
'ติดเชื้อ +2 ':'พบโรคที่ระดับความรุนแรง 4',}, inplace=True)  #แทนค่าข้อมูลตามที่เรากำหนด

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:6619: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)

In [39]:
set(alldb4['ov'])  #เชคข้อมูลคอลัมน์ ov ข้อมูลเป็นตามที่กำหนดแล้ว

{'พบโรคที่ระดับความรุนแรง 1',
 'พบโรคที่ระดับความรุนแรง 2',
 'พบโรคที่ระดับความรุนแรง 3',
 'พบโรคที่ระดับความรุนแรง 4',
 'ไม่พบโรค'}

###PartitionKey เป็นตัวเลข 5 หลัก (ตัวเลขเท่านั้น)
* เลือกมาเฉพาะข้อมูลที่เป็นตัวเลข 5 หลัก

In [40]:
set(alldb4['PartitionKey'])  #ดูค่าข้อมูลคอลัมน์ PartitionKey

{'04777',
 '01982',
 '02435',
 '01345',
 '01545',
 '00158',
 '01832',
 '02929',
 '01025',
 '01836',
 '02676',
 '02777',
 '00802',
 '00298',
 '00413',
 '00251',
 '180',
 '09004',
 '05103',
 '00367',
 '03333',
 '00604',
 '00658',
 '04753',
 '00955',
 '01064',
 '01574',
 '00520',
 '03004',
 '01583',
 '00022',
 '02295',
 '00741',
 '02298',
 '00215',
 '04782',
 '01812',
 '00410',
 '02012',
 '00058',
 '08930',
 '00905',
 '02756',
 '01346',
 '00318',
 '00831',
 '01480',
 '04640',
 '01478',
 '01148',
 '01671',
 '01506',
 '03133',
 '08314',
 '02622',
 '02624',
 '01042',
 '01920',
 '02488',
 '00518',
 '02424',
 '00744',
 '00763',
 '01088',
 '00243',
 '02523',
 '01468',
 '01715',
 '00042',
 '03221',
 '03319',
 '00963',
 '05228',
 '01101',
 '01901',
 '08477',
 '01785',
 '05362',
 '08903',
 '00583',
 '02978',
 '00913',
 '01865',
 '00824',
 '00402',
 '00030',
 '00111',
 '02589',
 '01122',
 '01452',
 '01063',
 '01441',
 '03329',
 '02384',
 '02224',
 '00165',
 '02967',
 '00900',
 '02022',
 '01401',
 '00732',
 '00117',
 '01708',
 '02490',
 '00124',
 '02928',
 '00543',
 '00648',
 '00803',
 '00081',
 '01453',
 '00817',
 '01513',
 '03019',
 '00360',
 '06725',
 '01264',
 '08950',
 '03158',
 '01950',
 '00822',
 '02743',
 '03094',
 '02566',
 '03362',
 '01487',
 '02330',
 '05127',
 '00901',
 '01090',
 '01918',
 '08969',
 '06030',
 '00256',
 '02044',
 '00297',
 '00523',
 '02279',
 '01029',
 '01051',
 '00577',
 '02365',
 '03512',
 '00401',
 '02737',
 '03121',
 '01125',
 '05122',
 '01551',
 '09008',
 '00735',
 '00879',
 '01443',
 '10982',
 '00814',
 '00790',
 '01410',
 '01898',
 '983',
 '00031',
 '05109',
 '02809',
 '04638',
 '00723',
 '01806',
 '01390',
 '02709',
 '08932',
 '02531',
 '06045',
 '01297',
 '01600',
 '01748',
 '03394',
 '00064',
 '01537',
 '02011',
 '05200',
 '00737',
 '05092',
 '02034',
 '00228',
 '00617',
 '00769',
 '02084',
 '02930',
 '01892',
 '01916',
 '01037',
 '04628',
 '01803',
 '01396',
 '00910',
 '03317',
 '00969',
 '02931',
 '00383',
 '00619',
 '01107',
 '0018',
 '00078',
 '05232',
 '01596',
 '01445',
 '02873',
 '01957',
 '03069',
 '00705',
 '00792',
 '01917',
 '03909',
 '02106',
 '01510',
 '02061',
 '02487',
 '02062',
 '01823',
 '06026',
 '01339',
 '05113',
 '02451',
 '00725',
 '00863',
 '03057',
 '02819',
 '05267',
 '01203',
 '09012',
 '00764',
 '00880',
 '02999',
 '04663',
 '01270',
 '03332',
 '02072',
 '1881',
 '05992',
 '08979',
 '00882',
 '00924',
 '00425',
 '02299',
 '04020',
 '00400',
 '02158',
 '01194',
 '00753',
 '03078',
 '241',
 '01747',
 '01963',
 '01002',
 '00616',
 '01938',
 '02154',
 '00861',
 '06009',
 '01365',
 '00522',
 '01885',
 '00254',
 '00202',
 '02071',
 '03034',
 '04793',
 '02544',
 '00756',
 '01548',
 '02029',
 '03934',
 '03515',
 '06061',
 '02353',
 '03062',
 '02050',
 '00354',
 '02807',
 '00014',
 '02080',
 '976',
 '00444',
 '02922',
 '00138',
 '01446',
 '00323',
 '03218',
 '03033',
 '02350',
 '00351',
 '02014',
 '02602',
 '01590',
 '01222',
 '02142',
 '01207',
 '00581',
 '02644',
 '02220',
 '08915',
 '0010',
 '10408',
 '04643',
 '01807',
 '01868',
 '00968',
 '01370',
 '00734',
 '02857',
 '03248',
 '02244',
 '00358',
 '01559',
 '03101',
 '03139',
 '00309',
 '01213',
 '01485',
 '02055',
 '00867',
 '00479',
 '01136',
 '02037',
 '01493',
 '00258',
 '01509',
 '01734',
 '01850',
 '04095',
 '00928',
 '00003',
 '00048',
 '05209',
 '01097',
 '01954',
 '02256',
 '05996',
 '01709',
 '02334',
 '00934',
 '01102',
 '00890',
 '01965',
 '02401',
 '02421',
 '02915',
 '08993',
 '01776',
 '11005',
 '03978',
 '02214',
 '00497',
 '00650',
 '01683',
 '01420',
 '01789',
 '01919',
 '01979',
 '02526',
 '03400',
 '06060',
 '02379',
 '02604',
 '03136',
 '00092',
 '00091',
 '01905',
 '01821',
 '00362',
 '00451',
 '01008',
 '00674',
 '01376',
 '01911',
 '03295',
 '03501',
 '06046',
 '02099',
 '02843',
 '05247',
 '01138',
 '01617',
 '00973',
 '01423',
 '03298',
 '00707',
 '00169',
 '00907',
 '02049',
 '02968',
 '04634',
 '02422',
 '02962',
 '09020',
 '01619',
 '05114',
 '00750',
 '00282',
 '05141',
 '01878',
 '01976',
 '01334',
 '01750',
 '06018',
 '01149',
 '01178',
 '00844',
 '01630',
 '01550',
 '00139',
 '01258',
 '02206',
 '05716',
 '02380',
 '02028',
 '01522',
 '00693',
 '00218',
 '01888',
 '02017',
 '01568',
 '03399',
 '00168',
 '00881',
 '00561',
 '03936',
 '00551',
 '02004',
 '01214',
 '00359',
 '01666',
 '01195',
 '00179',
 '02888',
 '00142',
 '01231',
 '02710',
 '00634',
 '01279',
 '00904',
 '00001',
 '01475',
 '10987',
 '06312',
 '01876',
 '196',
 '00757',
 '00866',
 '04812',
 '06043',
 '00491',
 '01579',
 '00260',
 '00736',
 '00940',
 '02073',
 '02821',
 '01058',
 '01491',
 '01240',
 '04732',
 '01292',
 '02486',
 '05336',
 '00115',
 '05961',
 '01081',
 '06020',
 '00281',
 '01864',
 '05987',
 '02732',
 '02423',
 '02580',
 '01196',
 '01156',
 '08926',
 '00469',
 '00718',
 '00386',
 '01793',
 '01567',
 '02975',
 '02175',
 '03165',
 '01460',
 '01631',
 '1022',
 '00668',
 '01371',
 '00528',
 '03152',
 '04788',
 '01072',
 '03002',
 '04974',
 '01154',
 '03279',
 '05292',
 '00719',
 '01884',
 '06047',
 '08914',
 '00925',
 '00178',
 '01533',
 '01763',
 '03227',
 '09013',
 '05098',
 '04688',
 '01887',
 '00306',
 '09043',
 '05233',
 '02417',
 '01152',
 '00121',
 '01116',
 '02013',
 '02403',
 '01439',
 '02827',
 '02859',
 '03403',
 '02678',
 '02889',
 '09024',
 '02268',
 '00101',
 '00287',
 '00869',
 '00738',
 '01163',
 '112',
 '01767',
 '02249',
 '00889',
 '02395',
 '00161',
 '01704',
 '02919',
 '03052',
 '01308',
 '02687',
 '03411',
 '05110',
 '00021',
 '01722',
 '01772',
 '00112',
 '00199',
 '01402',
 '02742',
 '02814',
 '08123',
 '05988',
 '01004',
 '02875',
 '08931',
 '04061',
 '11007',
 '02492',
 '01601',
 '02015',
 '02908',
 '03065',
 '02052',
 '00012',
 '00412',
 '03187',
 '00411',
 '05983',
 '00371',
 '01318',
 '02191',
 '00743',
 '05316',
 '00870',
 '02076',
 '02763',
 '02960',
 '00593',
 '02864',
 '03593',
 '02402',
 '01171',
 '09018',
 '11003',
 '00288',
 '01573',
 '04639',
 '00977',
 '01479',
 '01830',
 '00384',
 '02516',
 '00038',
 '08383',
 '01224',
 '03073',
 '01862',
 '01259',
 '02586',
 '01482',
 '00466',
 '01998',
 '06012',
 '00702',
 '03981',
 '00884',
 '00644',
 '01053',
 '00908',
 '01716',
 '01896',
 '00127',
 '01845',
 '08960',
 '06007',
 '03067',
 '03326',
 '01377',
 '00498',
 '01799',
 '01956',
 '01778',
 '00514',
 '00713',
 '01904',
 '03545',
 '05235',
 '00010',
 '000167',
 '05202',
 '04165',
 '00071',
 '0034',
 '05154',
 '01535',
 '03154',
 '06724',
 '01233',
 '179',
 '03925',
 '01660',
 '00363',
 '02750',
 '01945',
 '00097',
 '05806',
 '00261',
 '01141',
 '00667',
 '00615',
 '01942',
 '00044',
 '00966',
 '00673',
 '01198',
 '01437',
 '01937',
 '01359',
 '00341',
 '00538',
 '01687',
 '00338',
 '00134',
 '01013',
 '01455',
 '01632',
 '03220',
 '01592',
 '02366',
 '01068',
 '03125',
 '00276',
 '04607',
 '04658',
 '00982',
 '02836',
 '00767',
 '01562',
 '06006',
 '08956',
 '04046',
 '04649',
 '02164',
 '01735',
 '00462',
 '00424',
 '02812',
 '04642',
 '03508',
 '06005',
 '10964',
 '01667',
 '00013',
 '01131',
 '01486',
 '02434',
 '03278',
 '09033',
 '00060',
 '00016',
 '01239',
 '05965',
 '01243',
 '00126',
 '03322',
 '01974',
 '0005',
 '03511',
 '02563',
 '01959',
 '00098',
 '00714',
 '03436',
 '00434',
 '00799',
 '01005',
 '01357',
 '02872',
 '01883',
 '01386',
 '02378',
 '02467',
 '02808',
 '00200',
 '00171',
 '00489',
 '01030',
 '01625',
 '00272',
 '02271',
 '04651',
 '02639',
 '02652',
 '01754',
 '00563',
 '02407',
 '04648',
 '01039',
 '00728',
 '00804',
 '00862',
 '08909',
 '02094',
 '08921',
 '02184',
 '01523',
 '09036',
 '00516',
 '01721',
 '02773',
 '00842',
 '10963',
 '00250',
 '00395',
 '06008',
 '04074',
 '02854',
 '02956',
 '00986',
 '01256',
 '03327',
 '00083\u200b',
 '03417',
 '03424',
 '02152',
 '01531',
 '01824',
 '01407',
 '04679',
 '177',
 '02086',
 '03100',
 '00845',
 '01248',
 '107',
 '02124',
 '01113',
 '00749',
 '01155',
 '00283',
 '03224',
 '03324',
 '01740',
 '06013',
 '02985',
 '01326',
 '00180',
 '02032',
 '00488',
 '00835',
 '03056',
 '00086',
 '00399',
 '00833',
 '00274',
 '01166',
 '00987',
 '03381',
 '01738',
 '00722',
 '00849',
 '00143',
 '04785',
 '02863',
 '02933',
 '03273',
 '01079',
 '01659',
 '02068',
 '02408',
 '02593',
 '01742',
 '00002',
 '00692',
 '00533',
 '04674',
 '01873',
 '08254',
 '00241',
 '06064',
 '00136',
 '10999',
 '00063',
 '00443',
 '10962',
 '01296',
 '002.5',
 '01209',
 '01257',
 '01707',
 '02223',
 '00778',
 '01753',
 '04789',
 '00167',
 '00290',
 '01098',
 '01382',
 '02584',
 '04631',
 '04766',
 '89',
 '02847',
 '01881',
 '00190',
 '03425',
 '04668',
 '04625',
 '03049',
 '02251',
 '02060',
 '00660',
 '00605',
 '02934',
 '01808',
 '00960',
 '01183',
 '02390',
 '00152',
 '02123',
 '00780',
 '00494',
 '01664',
 '01569',
 '01253',
 '05963',
 '01861',
 '00224',
 '04116',
 '10984',
 '01110',
 '02938',
 '05115',
 '01299',
 '03008',
 '04075',
 '03030',
 '23',
 '04191',
 '01822',
 '00418',
 '00102',
 '02619',
 '03068',
 '05255',
 '02995',
 '05172',
 '04054',
 '02238',
 '00816',
 '00380',
 '10983',
 '001',
 '00262',
 '01330',
 '01837',
 '06024',
 '02019',
 '00393',
 '01170',
 '02564',
 '01317',
 '00310',
 '02683',
 '01242',
 '00172',
 '03181',
 '01811',
 '02162',
 '02848',
 '00376',
 '02746',
 '01056',
 '02079',
 '01273',
 '08977',
 '01589',
 '00776',
 '01012',
 '00398',
 '01033',
 '01500',
 '04632',
 '00640',
 '02769',
 '04622',
 '01928',
 '09000',
 '00245',
 '03366',
 '00585',
 '02559',
 '00602',
 '03331',
 '00626',
 '09030',
 '01305',
 '02338',
 '10971',
 '00800',
 '05318',
 '08942',
 '01397',
 '01809',
 '01665',
 '00340',
 '00789',
 '01463',
 '02892',
 '01838',
 '01225',
 '00774',
 '02534',
 '01762',
 '00647',
 '02119',
 '00320',
 '02459',
 '121',
 '00868',
 '00275',
 '00073',
 '03107',
 '02936',
 '00206',
 '05981',
 '00268',
 '01908',
 '00565',
 '05244',
 '02484',
 '00703',
 '01320',
 '01940',
 '01512',
 '00156',
 '02070',
 '00325',
 '01331',
 '00567',
 '01210',
 '00499',
 '01009',
 '01779',
 '03933',
 '01172',
 '05720',
 '04695',
 '01654',
 '00999',
 '01352',
 '00460',
 '01360',
 '00486',
 '00751',
 '00984',
 ...}

In [41]:
alldb5 = alldb4[(alldb4['PartitionKey'].astype(str).str.isdigit()) & (alldb4['PartitionKey'].str.len() == 5)]  #เลือกข้อมูลที่เป็นตัวเลข 5 หลักเท่านั้น
alldb5

,user,RowKey,date,ov,phone,site,time,urine,PartitionKey
190,06223,kfpwuaqldj.png,2022-03-23,ไม่พบโรค,Xiaomi 21081111RG,13777,16-31-45,ปกติ (เหลืองใส),00000
191,12015,00859DB9-1BD9-4825-B246-3DC25EFD1924,2022-03-30,พบโรคที่ระดับความรุนแรง 4,"iPhone12,3",06307,14-46-08,ปกติ (เหลืองใส),00001
192,91811,1376ACA2-AFA5-4457-967A-D2FCF908E6A5,2022-03-30,พบโรคที่ระดับความรุนแรง 4,"iPhone14,3",05328,15-27-45,ปกติ (เหลืองใส),00001
193,95821,1914EE67-CD8F-47EE-A968-2772911AA5DF,2022-03-30,พบโรคที่ระดับความรุนแรง 3,"iPhone13,4",06302,10-16-46,ปกติ (เหลืองใส),00001
194,13361,1A219EE7-3647-4D7D-A8C0-AE638E69D889,2022-03-29,พบโรคที่ระดับความรุนแรง 3,"iPhone9,4",05059,12-26-38,ปกติ (เหลืองใส),00001
...,...,...,...,...,...,...,...,...,...
39812,99999,F45E78D3-7D89-47A3-8207-C705377E0E0A,2022-03-11,พบโรคที่ระดับความรุนแรง 1,"iPhone14,2",99999,11-36-34,ขุ่น,99999
39813,99999,lnlohgqckf.png,2022-03-10,ไม่พบโรค,Samsung SM-G998B,99999,18-10-29,มีตะกอน,99999
39814,99999,vkdocpmjiv.png,2022-03-10,พบโรคที่ระดับความรุนแรง 1,Samsung SM-G998B,99999,12-14-41,"ขุ่น, มีเม็ดเลือดแดง",99999
39815,99999,vrvyfnvayq.png,2022-03-10,พบโรคที่ระดับความรุนแรง 1,Samsung SM-G998B,99999,13-58-01,ปกติ (เหลืองใส),99999
39816,99999,zuhbtvyrce.png,2022-03-10,พบโรคที่ระดับความรุนแรง 1,Samsung SM-G998B,99999,13-57-58,ปกติ (เหลืองใส),99999

##ตารางไฟล์ alldb

In [42]:
alldb5

,user,RowKey,date,ov,phone,site,time,urine,PartitionKey
190,06223,kfpwuaqldj.png,2022-03-23,ไม่พบโรค,Xiaomi 21081111RG,13777,16-31-45,ปกติ (เหลืองใส),00000
191,12015,00859DB9-1BD9-4825-B246-3DC25EFD1924,2022-03-30,พบโรคที่ระดับความรุนแรง 4,"iPhone12,3",06307,14-46-08,ปกติ (เหลืองใส),00001
192,91811,1376ACA2-AFA5-4457-967A-D2FCF908E6A5,2022-03-30,พบโรคที่ระดับความรุนแรง 4,"iPhone14,3",05328,15-27-45,ปกติ (เหลืองใส),00001
193,95821,1914EE67-CD8F-47EE-A968-2772911AA5DF,2022-03-30,พบโรคที่ระดับความรุนแรง 3,"iPhone13,4",06302,10-16-46,ปกติ (เหลืองใส),00001
194,13361,1A219EE7-3647-4D7D-A8C0-AE638E69D889,2022-03-29,พบโรคที่ระดับความรุนแรง 3,"iPhone9,4",05059,12-26-38,ปกติ (เหลืองใส),00001
...,...,...,...,...,...,...,...,...,...
39812,99999,F45E78D3-7D89-47A3-8207-C705377E0E0A,2022-03-11,พบโรคที่ระดับความรุนแรง 1,"iPhone14,2",99999,11-36-34,ขุ่น,99999
39813,99999,lnlohgqckf.png,2022-03-10,ไม่พบโรค,Samsung SM-G998B,99999,18-10-29,มีตะกอน,99999
39814,99999,vkdocpmjiv.png,2022-03-10,พบโรคที่ระดับความรุนแรง 1,Samsung SM-G998B,99999,12-14-41,"ขุ่น, มีเม็ดเลือดแดง",99999
39815,99999,vrvyfnvayq.png,2022-03-10,พบโรคที่ระดับความรุนแรง 1,Samsung SM-G998B,99999,13-58-01,ปกติ (เหลืองใส),99999
39816,99999,zuhbtvyrce.png,2022-03-10,พบโรคที่ระดับความรุนแรง 1,Samsung SM-G998B,99999,13-57-58,ปกติ (เหลืองใส),99999

In [43]:
alldb2.isnull().any()  #เชค Missing พบว่าไม่มี Missing

user            False
RowKey          False
date            False
ov              False
phone           False
site            False
time            False
urine           False
PartitionKey    False
dtype: bool

#Datahospital_list

In [44]:
hospital_list = pd.read_excel(os.path.join(path,'hospital_list.xlsx'))   #ข้อมูล Datahospital_list
hospital_list

,hcode,name,zone_code,zone_name,provincecode,province,amphurcode,amphur,tamboncode,tambon,code4,name5,code9,name10,short_thai,short_english
0,00001,สำนักงานสาธารณสุขจังหวัดสมุทรปราการ,6,สาขาพื้นที่(ระยอง),11.0,สมุทรปราการ,1.0,เมืองสมุทรปราการ,1.0,ปากน้ำ,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,NaN,สป,SPK
1,00002,สำนักงานสาธารณสุขจังหวัดนนทบุรี,4,สาขาพื้นที่(สระบุรี),12.0,นนทบุรี,1.0,เมืองนนทบุรี,4.0,บางกระสอ,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,NaN,นบ,NBI
2,00003,สำนักงานสาธารณสุขจังหวัดปทุมธานี,4,สาขาพื้นที่(สระบุรี),13.0,ปทุมธานี,1.0,เมืองปทุมธานี,1.0,บางปรอก,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,NaN,ปท,PTE
3,00004,สำนักงานสาธารณสุขจังหวัดพระนครศรีอยุธยา,4,สาขาพื้นที่(สระบุรี),14.0,พระนครศรีอยุธยา,1.0,พระนครศรีอยุธยา,3.0,หอรัตนไชย,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,NaN,อย,AYA
4,00005,สำนักงานสาธารณสุขจังหวัดอ่างทอง,4,สาขาพื้นที่(สระบุรี),15.0,อ่างทอง,1.0,เมืองอ่างทอง,8.0,บ้านอิฐ,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,NaN,อท,ATG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17098,99990,ศูนย์สุขภาพชุมชนโรงพยาบาลอุตรดิตถ์(สาขา 2 วัดท...,2,สาขาพื้นที่(พิษณุโลก),53.0,อุตรดิตถ์,1.0,เมืองอุตรดิตถ์,1.0,ท่าอิฐ,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,อต,UTT
17099,99991,ศูนย์สุขภาพชุมชนโรงพยาบาลกุยบุรี,5,สาขาพื้นที่(ราชบุรี),77.0,ประจวบคีรีขันธ์,2.0,กุยบุรี,1.0,กุยบุรี,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,ปข,PKN
17100,99993,ศูนย์สุขภาพชุมชนตำบลวัดเพลง,5,สาขาพื้นที่(ราชบุรี),70.0,ราชบุรี,9.0,วัดเพลง,3.0,วัดเพลง,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,รบ,RBR
17101,99996,คลินิกทันตกรรม สสจ.ศรีสะเกษ,10,สาขาพื้นที่(อุบลราชธานี),33.0,ศรีสะเกษ,1.0,เมืองศรีสะเกษ,11.0,โพนข่า,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,ศก,SSK
17102,99998,ศูนย์สุขภาพชุมชนตำบลบางแพ,5,สาขาพื้นที่(ราชบุรี),70.0,ราชบุรี,6.0,บางแพ,2.0,วังเย็น,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,รบ,RBR

#รวมตาราง alldb และ hospital_list

In [45]:
data_merge = alldb5.merge(hospital_list,how='left',left_on='site',right_on='hcode')  #รวมตารางโดยให้ alldb5 เป็น ตารางหลัก เชื่อมด้วยคีย์หลัก site และ คีย์รองคือ hcode
data_merge

,user,RowKey,date,ov,phone,site,time,urine,PartitionKey,hcode,...,amphurcode,amphur,tamboncode,tambon,code4,name5,code9,name10,short_thai,short_english
0,06223,kfpwuaqldj.png,2022-03-23,ไม่พบโรค,Xiaomi 21081111RG,13777,16-31-45,ปกติ (เหลืองใส),00000,13777,...,1.0,เมืองขอนแก่น,1.0,ในเมือง,12.0,โรงพยาบาล นอก สธ.,NaN,NaN,ขก,KKN
1,12015,00859DB9-1BD9-4825-B246-3DC25EFD1924,2022-03-30,พบโรคที่ระดับความรุนแรง 4,"iPhone12,3",06307,14-46-08,ปกติ (เหลืองใส),00001,06307,...,7.0,พิชัย,2.0,บ้านดารา,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,อต,UTT
2,91811,1376ACA2-AFA5-4457-967A-D2FCF908E6A5,2022-03-30,พบโรคที่ระดับความรุนแรง 4,"iPhone14,3",05328,15-27-45,ปกติ (เหลืองใส),00001,05328,...,18.0,ฆ้องชัย,3.0,โคกสะอาด,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,กส,KSN
3,95821,1914EE67-CD8F-47EE-A968-2772911AA5DF,2022-03-30,พบโรคที่ระดับความรุนแรง 3,"iPhone13,4",06302,10-16-46,ปกติ (เหลืองใส),00001,06302,...,5.0,ฟากท่า,4.0,สองห้อง,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,อต,UTT
4,13361,1A219EE7-3647-4D7D-A8C0-AE638E69D889,2022-03-29,พบโรคที่ระดับความรุนแรง 3,"iPhone9,4",05059,12-26-38,ปกติ (เหลืองใส),00001,05059,...,10.0,นาดูน,6.0,หัวดง,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,มค,MKM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37891,99999,F45E78D3-7D89-47A3-8207-C705377E0E0A,2022-03-11,พบโรคที่ระดับความรุนแรง 1,"iPhone14,2",99999,11-36-34,ขุ่น,99999,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37892,99999,lnlohgqckf.png,2022-03-10,ไม่พบโรค,Samsung SM-G998B,99999,18-10-29,มีตะกอน,99999,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37893,99999,vkdocpmjiv.png,2022-03-10,พบโรคที่ระดับความรุนแรง 1,Samsung SM-G998B,99999,12-14-41,"ขุ่น, มีเม็ดเลือดแดง",99999,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37894,99999,vrvyfnvayq.png,2022-03-10,พบโรคที่ระดับความรุนแรง 1,Samsung SM-G998B,99999,13-58-01,ปกติ (เหลืองใส),99999,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37895,99999,zuhbtvyrce.png,2022-03-10,พบโรคที่ระดับความรุนแรง 1,Samsung SM-G998B,99999,13-57-58,ปกติ (เหลืองใส),99999,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

##กำจัดค่า Missing

In [46]:
data_merge.isnull().any()  #เชค Missing พบว่ายังมีค่า Missing

user             False
RowKey           False
date             False
ov               False
phone            False
site             False
time             False
urine            False
PartitionKey     False
hcode             True
name              True
zone_code         True
zone_name         True
provincecode      True
province          True
amphurcode        True
amphur            True
tamboncode        True
tambon            True
code4             True
name5             True
code9             True
name10            True
short_thai        True
short_english     True
dtype: bool

In [47]:
data_merge1 = data_merge.dropna()  #จัดการ Missing ด้วยการ drop na
data_merge1

,user,RowKey,date,ov,phone,site,time,urine,PartitionKey,hcode,...,amphurcode,amphur,tamboncode,tambon,code4,name5,code9,name10,short_thai,short_english
1,12015,00859DB9-1BD9-4825-B246-3DC25EFD1924,2022-03-30,พบโรคที่ระดับความรุนแรง 4,"iPhone12,3",06307,14-46-08,ปกติ (เหลืองใส),00001,06307,...,7.0,พิชัย,2.0,บ้านดารา,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,อต,UTT
2,91811,1376ACA2-AFA5-4457-967A-D2FCF908E6A5,2022-03-30,พบโรคที่ระดับความรุนแรง 4,"iPhone14,3",05328,15-27-45,ปกติ (เหลืองใส),00001,05328,...,18.0,ฆ้องชัย,3.0,โคกสะอาด,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,กส,KSN
3,95821,1914EE67-CD8F-47EE-A968-2772911AA5DF,2022-03-30,พบโรคที่ระดับความรุนแรง 3,"iPhone13,4",06302,10-16-46,ปกติ (เหลืองใส),00001,06302,...,5.0,ฟากท่า,4.0,สองห้อง,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,อต,UTT
4,13361,1A219EE7-3647-4D7D-A8C0-AE638E69D889,2022-03-29,พบโรคที่ระดับความรุนแรง 3,"iPhone9,4",05059,12-26-38,ปกติ (เหลืองใส),00001,05059,...,10.0,นาดูน,6.0,หัวดง,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,มค,MKM
5,28241,1AFBC992-AF2F-4F97-AE6D-443F30ED8402,2022-03-31,ไม่พบโรค,"iPhone13,3",06334,14-57-41,ปกติ (เหลืองใส),00001,06334,...,9.0,ทองแสนขัน,4.0,น้ำพี้,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,อต,UTT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37879,68768,B7F36631-D2C4-4EB5-852D-790BFAFDFD71,2022-03-24,พบโรคที่ระดับความรุนแรง 2,"iPhone11,8",11088,10-30-22,ปกติ (เหลืองใส),89170,11088,...,14.0,ห้วยผึ้ง,3.0,นิคมห้วยผึ้ง,7.0,โรงพยาบาลชุมชน,21.0,2.1 ทุติยภูมิระดับต้น,กส,KSN
37880,68768,899A7591-50C9-40BC-9746-A831A08DE980,2022-03-24,ไม่พบโรค,"iPhone11,8",11088,10-29-37,ปกติ (เหลืองใส),90470,11088,...,14.0,ห้วยผึ้ง,3.0,นิคมห้วยผึ้ง,7.0,โรงพยาบาลชุมชน,21.0,2.1 ทุติยภูมิระดับต้น,กส,KSN
37881,68768,BF39F27C-1B43-4C97-A034-D7A579BED2B6,2022-03-24,พบโรคที่ระดับความรุนแรง 1,"iPhone11,8",11088,10-24-40,ปกติ (เหลืองใส),91123,11088,...,14.0,ห้วยผึ้ง,3.0,นิคมห้วยผึ้ง,7.0,โรงพยาบาลชุมชน,21.0,2.1 ทุติยภูมิระดับต้น,กส,KSN
37882,68768,D8A3A9EA-929E-4CEB-BFDF-C9BE093EA663,2022-03-24,พบโรคที่ระดับความรุนแรง 1,"iPhone11,8",11088,10-25-32,ปกติ (เหลืองใส),99444,11088,...,14.0,ห้วยผึ้ง,3.0,นิคมห้วยผึ้ง,7.0,โรงพยาบาลชุมชน,21.0,2.1 ทุติยภูมิระดับต้น,กส,KSN
37883,99771,E04D3D60-B916-40A1-AE77-91CCD89DD084,2022-03-31,ไม่พบโรค,"iPhone10,5",05396,11-03-40,ปกติ (เหลืองใส),99771,05396,...,10.0,คำม่วง,9.0,เนินยาง,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,กส,KSN

In [48]:
removes = data_merge.shape[0] - data_merge1.shape[0]    #เชคว่าจากการดรอปข้อมูลหายกี่เปอร์เซนต์ ซึ่งพบว่าหาย 1.8497994511294067% ของข้อมูลทั้งหมด ยอมรับได้
print(f'size before drop = {data_merge.shape[0]}')
print(f'size aftre drop = {data_merge1.shape[0]}')
print(f'we loss {100*(removes/data_merge.shape[0])}% of data')

size before drop = 37896
size aftre drop = 37195
we loss 1.8497994511294067% of data

In [49]:
print(data_merge.shape)   #จำนวนแถวก่อนDropna
print(data_merge1.shape)   #จำนวนแถวหลังDropna

(37896, 25)
(37195, 25)

In [50]:
data_merge1.head()  #เชคหัวคอลัมน์

,user,RowKey,date,ov,phone,site,time,urine,PartitionKey,hcode,...,amphurcode,amphur,tamboncode,tambon,code4,name5,code9,name10,short_thai,short_english
1,12015,00859DB9-1BD9-4825-B246-3DC25EFD1924,2022-03-30,พบโรคที่ระดับความรุนแรง 4,"iPhone12,3",06307,14-46-08,ปกติ (เหลืองใส),00001,06307,...,7.0,พิชัย,2.0,บ้านดารา,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,อต,UTT
2,91811,1376ACA2-AFA5-4457-967A-D2FCF908E6A5,2022-03-30,พบโรคที่ระดับความรุนแรง 4,"iPhone14,3",05328,15-27-45,ปกติ (เหลืองใส),00001,05328,...,18.0,ฆ้องชัย,3.0,โคกสะอาด,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,กส,KSN
3,95821,1914EE67-CD8F-47EE-A968-2772911AA5DF,2022-03-30,พบโรคที่ระดับความรุนแรง 3,"iPhone13,4",06302,10-16-46,ปกติ (เหลืองใส),00001,06302,...,5.0,ฟากท่า,4.0,สองห้อง,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,อต,UTT
4,13361,1A219EE7-3647-4D7D-A8C0-AE638E69D889,2022-03-29,พบโรคที่ระดับความรุนแรง 3,"iPhone9,4",05059,12-26-38,ปกติ (เหลืองใส),00001,05059,...,10.0,นาดูน,6.0,หัวดง,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,มค,MKM
5,28241,1AFBC992-AF2F-4F97-AE6D-443F30ED8402,2022-03-31,ไม่พบโรค,"iPhone13,3",06334,14-57-41,ปกติ (เหลืองใส),00001,06334,...,9.0,ทองแสนขัน,4.0,น้ำพี้,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,อต,UTT

##เลือกมาเฉพาะคอมลัมน์ที่ต้องการใช้

In [51]:
datause = data_merge1[['user','RowKey','date','ov','phone','site','time','urine','PartitionKey','name','zone_name','province','amphur','tambon','short_thai','short_english']]
datause

,user,RowKey,date,ov,phone,site,time,urine,PartitionKey,name,zone_name,province,amphur,tambon,short_thai,short_english
1,12015,00859DB9-1BD9-4825-B246-3DC25EFD1924,2022-03-30,พบโรคที่ระดับความรุนแรง 4,"iPhone12,3",06307,14-46-08,ปกติ (เหลืองใส),00001,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านเกาะ ตำบลบ้านดารา,สาขาพื้นที่(พิษณุโลก),อุตรดิตถ์,พิชัย,บ้านดารา,อต,UTT
2,91811,1376ACA2-AFA5-4457-967A-D2FCF908E6A5,2022-03-30,พบโรคที่ระดับความรุนแรง 4,"iPhone14,3",05328,15-27-45,ปกติ (เหลืองใส),00001,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านโคกประสิทธิ์,สาขาพื้นที่(ขอนแก่น),กาฬสินธุ์,ฆ้องชัย,โคกสะอาด,กส,KSN
3,95821,1914EE67-CD8F-47EE-A968-2772911AA5DF,2022-03-30,พบโรคที่ระดับความรุนแรง 3,"iPhone13,4",06302,10-16-46,ปกติ (เหลืองใส),00001,โรงพยาบาลส่งเสริมสุขภาพตำบลสองห้อง,สาขาพื้นที่(พิษณุโลก),อุตรดิตถ์,ฟากท่า,สองห้อง,อต,UTT
4,13361,1A219EE7-3647-4D7D-A8C0-AE638E69D889,2022-03-29,พบโรคที่ระดับความรุนแรง 3,"iPhone9,4",05059,12-26-38,ปกติ (เหลืองใส),00001,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านดอนดู่,สาขาพื้นที่(ขอนแก่น),มหาสารคาม,นาดูน,หัวดง,มค,MKM
5,28241,1AFBC992-AF2F-4F97-AE6D-443F30ED8402,2022-03-31,ไม่พบโรค,"iPhone13,3",06334,14-57-41,ปกติ (เหลืองใส),00001,โรงพยาบาลส่งเสริมสุขภาพตำบลน้ำพี้,สาขาพื้นที่(พิษณุโลก),อุตรดิตถ์,ทองแสนขัน,น้ำพี้,อต,UTT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37879,68768,B7F36631-D2C4-4EB5-852D-790BFAFDFD71,2022-03-24,พบโรคที่ระดับความรุนแรง 2,"iPhone11,8",11088,10-30-22,ปกติ (เหลืองใส),89170,โรงพยาบาลห้วยผึ้ง,สาขาพื้นที่(ขอนแก่น),กาฬสินธุ์,ห้วยผึ้ง,นิคมห้วยผึ้ง,กส,KSN
37880,68768,899A7591-50C9-40BC-9746-A831A08DE980,2022-03-24,ไม่พบโรค,"iPhone11,8",11088,10-29-37,ปกติ (เหลืองใส),90470,โรงพยาบาลห้วยผึ้ง,สาขาพื้นที่(ขอนแก่น),กาฬสินธุ์,ห้วยผึ้ง,นิคมห้วยผึ้ง,กส,KSN
37881,68768,BF39F27C-1B43-4C97-A034-D7A579BED2B6,2022-03-24,พบโรคที่ระดับความรุนแรง 1,"iPhone11,8",11088,10-24-40,ปกติ (เหลืองใส),91123,โรงพยาบาลห้วยผึ้ง,สาขาพื้นที่(ขอนแก่น),กาฬสินธุ์,ห้วยผึ้ง,นิคมห้วยผึ้ง,กส,KSN
37882,68768,D8A3A9EA-929E-4CEB-BFDF-C9BE093EA663,2022-03-24,พบโรคที่ระดับความรุนแรง 1,"iPhone11,8",11088,10-25-32,ปกติ (เหลืองใส),99444,โรงพยาบาลห้วยผึ้ง,สาขาพื้นที่(ขอนแก่น),กาฬสินธุ์,ห้วยผึ้ง,นิคมห้วยผึ้ง,กส,KSN
37883,99771,E04D3D60-B916-40A1-AE77-91CCD89DD084,2022-03-31,ไม่พบโรค,"iPhone10,5",05396,11-03-40,ปกติ (เหลืองใส),99771,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านสูงเนิน,สาขาพื้นที่(ขอนแก่น),กาฬสินธุ์,คำม่วง,เนินยาง,กส,KSN

#นำข้อมูลไปใช้งาน

In [52]:
datause.to_csv('datause.csv') 
datause.to_csv(os.path.join(path,'datause.csv'))